// NeuronCite -- local, privacy-preserving semantic document search engine.
// Copyright (C) 2026 NeuronCite Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Integration tests for the pdfium fallback extraction path.
//
// This module tests three synthetic PDFs (generated by neuroncite-testgen)
// that the default pdf-extract backend cannot parse. Each PDF lives in a
// subfolder named after the specific failure mode it triggers:
//
// - cross-reference-error/  Synthetic PDF with corrupted xref table.
//   pdf-extract returns an error; pdfium also fails (triple corruption).
//
// - cid-range-panic/  Synthetic PDF with malformed CID font CMap stream.
//   pdf-extract panics in the CID-range font table parser.
//
// - type1-font-panic/  Synthetic PDF with malformed Type1 FontFile stream.
//   pdf-extract panics in the Type1 font encoding data parser.
//
// The CID-range and Type1 PDFs contain Helvetica-rendered text that pdfium
// extracts after the fallback chain catches the pdf-extract panic. The
// xref-corruption PDF defeats both backends.
//
// Regenerate fixtures: cargo run -p neuroncite-testgen
//
// This module is compiled when the "pdfium" feature is enabled (see
// integration/mod.rs). At runtime, the tests require pdfium.dll /
// libpdfium.so to be available.

use std::path::{Path, PathBuf};
use std::sync::mpsc;
use std::time::Duration;

use neuroncite_core::{Chunk, ExtractionBackend, IndexConfig, PageText, StorageMode};
use neuroncite_store::{self as store, ChunkInsert};

use crate::common;

/// Per-file timeout for PDF text extraction. Scanned and OCR-heavy PDFs may
/// take longer than typical text-based PDFs. 60 seconds is a conservative
/// upper bound that avoids false timeouts on slow machines while still
/// catching infinite loops.
const EXTRACT_TIMEOUT: Duration = Duration::from_secs(60);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Mapping of each problematic PDF to its subfolder name under tests/PDFs/ocr/.
/// The subfolder name describes the specific pdf-extract failure mode.
const OCR_PDF_ENTRIES: [(&str, &str); 3] = [
    (
        "cross-reference-error",
        "synthetic_statistics_xref_corruption.pdf",
    ),
    ("cid-range-panic", "synthetic_finance_cid_range.pdf"),
    (
        "type1-font-panic",
        "synthetic_forecasting_type1_encoding.pdf",
    ),
];

/// Returns the absolute path to the `tests/PDFs/ocr/` directory containing
/// real-world PDFs that require pdfium or OCR fallback for text extraction.
/// Returns `None` when the directory does not exist (the OCR test corpus
/// has not been provisioned in this environment).
fn ocr_pdf_dir() -> Option<PathBuf> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent() // crates/
        .and_then(|p| p.parent()) // workspace root
        .expect("failed to resolve workspace root from CARGO_MANIFEST_DIR");
    let pdf_dir = workspace_root.join("tests").join("PDFs").join("ocr");
    if pdf_dir.is_dir() {
        Some(pdf_dir)
    } else {
        None
    }
}

/// Returns the absolute paths to all three OCR test PDFs, or `None` when
/// the OCR test directory or any of the expected PDF files is missing.
/// Each PDF resides in a subfolder named after its pdf-extract failure mode.
fn ocr_pdf_paths() -> Option<Vec<PathBuf>> {
    let dir = ocr_pdf_dir()?;
    let mut paths = Vec::with_capacity(OCR_PDF_ENTRIES.len());
    for (subfolder, filename) in &OCR_PDF_ENTRIES {
        let path = dir.join(subfolder).join(filename);
        if !path.is_file() {
            return None;
        }
        paths.push(path);
    }
    Some(paths)
}

/// Returns the absolute path to a specific OCR test PDF by its problem
/// subfolder name (e.g., "cross-reference-error", "cid-range-panic",
/// "type1-font-panic"). Returns `None` when the directory or file is missing.
fn ocr_pdf_by_problem(problem: &str) -> Option<PathBuf> {
    let dir = ocr_pdf_dir()?;
    let (_, filename) = OCR_PDF_ENTRIES.iter().find(|(sub, _)| *sub == problem)?;
    let path = dir.join(problem).join(filename);
    if path.is_file() { Some(path) } else { None }
}

/// Returns an IndexConfig for OCR pipeline tests using word-window chunking.
fn ocr_test_config(directory: &Path) -> IndexConfig {
    IndexConfig {
        directory: directory.to_path_buf(),
        model_name: "stub-model".to_string(),
        chunk_strategy: "word".to_string(),
        chunk_size: Some(300),
        chunk_overlap: Some(50),
        max_words: None,
        ocr_language: "eng".to_string(),
        embedding_storage_mode: StorageMode::SqliteBlob,
        vector_dimension: 4,
    }
}

/// Extracts pages from a PDF file with a per-file timeout and panic catching.
/// Returns `Some(pages)` on success, `None` on error/panic/timeout. The
/// `backend` parameter is forwarded to `neuroncite_pdf::extract_pages` as
/// the backend preference.
fn extract_with_timeout_and_backend(
    pdf_path: &Path,
    timeout: Duration,
    backend: Option<&'static str>,
) -> Option<Vec<PageText>> {
    let path = pdf_path.to_path_buf();
    let (tx, rx) = mpsc::channel();

    // Use 8 MB stack to accommodate pdfium FFI C-library call frames during
    // PDF font parsing (CID-range, Type1). The default ~2 MB thread stack
    // overflows when multiple pdfium extractions run concurrently in the test
    // harness because each pdfium FFI call chain consumes ~1-2 MB of stack.
    std::thread::Builder::new()
        .stack_size(8 * 1024 * 1024)
        .spawn(move || {
            let result = std::panic::catch_unwind(move || {
                neuroncite_pdf::extract_pages(&path, backend, None)
            });
            let _ = tx.send(result);
        })
        .expect("failed to spawn extraction thread");

    match rx.recv_timeout(timeout) {
        Ok(Ok(Ok(extraction))) => Some(extraction.pages),
        Ok(Ok(Err(e))) => {
            eprintln!("  extraction error for {}: {e}", pdf_path.display());
            None
        }
        Ok(Err(_)) => {
            eprintln!(
                "  extraction panicked for {} (third-party font parser)",
                pdf_path.display()
            );
            None
        }
        Err(_) => {
            eprintln!(
                "  extraction timed out for {} after {timeout:?}",
                pdf_path.display()
            );
            None
        }
    }
}

/// Returns true if the page list contains at least one page with more
/// than `min_chars` non-whitespace characters.
fn has_substantial_text(pages: &[PageText], min_chars: usize) -> bool {
    pages
        .iter()
        .any(|p| p.content.chars().filter(|c| !c.is_whitespace()).count() > min_chars)
}

/// Checks whether pdfium is available at runtime by writing a minimal
/// valid PDF to a temporary file and attempting pdfium extraction on it.
/// Returns true if pdfium.dll / libpdfium.so was loaded successfully.
///
/// The probe creates a zero-page PDF to minimize I/O overhead. If the
/// pdfium shared library cannot be loaded, the error message will contain
/// "bind to pdfium" or "LoadLibrary". Any other error (PDF parsing, etc.)
/// indicates that pdfium IS loaded but the probe PDF was rejected.
fn is_pdfium_available() -> bool {
    use std::io::Write;

    // Minimal valid PDF structure: catalog and empty page tree.
    let probe_pdf = b"%PDF-1.0\n\
        1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n\
        2 0 obj\n<< /Type /Pages /Kids [] /Count 0 >>\nendobj\n\
        xref\n0 3\n\
        0000000000 65535 f \n\
        0000000009 00000 n \n\
        0000000058 00000 n \n\
        trailer\n<< /Size 3 /Root 1 0 R >>\nstartxref\n0\n%%EOF";

    let tmp = match tempfile::NamedTempFile::with_suffix(".pdf") {
        Ok(mut t) => {
            if t.write_all(probe_pdf).is_err() || t.flush().is_err() {
                return false;
            }
            t
        }
        Err(_) => return false,
    };

    match neuroncite_pdf::extract_pages(tmp.path(), Some("pdfium"), None) {
        Ok(_) => true,
        Err(e) => {
            let msg = format!("{e}");
            // If the error is about loading the pdfium shared library,
            // pdfium is not installed on this system.
            let is_binding_error = msg.contains("bind to pdfium") || msg.contains("LoadLibrary");
            !is_binding_error
        }
    }
}

// ---------------------------------------------------------------------------
// T-OCR-001: pdf-extract fails for all 3 OCR PDFs
// ---------------------------------------------------------------------------

/// T-OCR-001: Confirms that the default pdf-extract backend cannot extract
/// text from the three OCR test PDFs. Each file either returns an error or
/// triggers a panic (caught by catch_unwind). This test validates the
/// premise that these PDFs require fallback backends.
#[test]
fn t_ocr_001_pdf_extract_fails_for_ocr_pdfs() {
    let paths = match ocr_pdf_paths() {
        Some(p) => p,
        None => {
            eprintln!("skipping: OCR test PDFs not found. Run: cargo run -p neuroncite-testgen");
            return;
        }
    };

    for pdf_path in &paths {
        let result =
            extract_with_timeout_and_backend(pdf_path, EXTRACT_TIMEOUT, Some("pdf-extract"));

        match result {
            Some(pages) => {
                // pdf-extract may return pages but with no usable text.
                // Check that the text quality is insufficient.
                let total_non_ws: usize = pages
                    .iter()
                    .map(|p| p.content.chars().filter(|c| !c.is_whitespace()).count())
                    .sum();
                eprintln!(
                    "  pdf-extract returned {} pages ({} non-ws chars) for {}",
                    pages.len(),
                    total_non_ws,
                    pdf_path.file_name().unwrap_or_default().to_string_lossy()
                );
                // It is acceptable for pdf-extract to return pages with
                // zero or very little text (quality heuristics would trigger
                // fallback in auto mode). The key property is that the text
                // is NOT sufficient for meaningful search.
            }
            None => {
                // Expected: extraction failed or panicked.
                eprintln!(
                    "  pdf-extract failed/panicked for {} (expected)",
                    pdf_path.file_name().unwrap_or_default().to_string_lossy()
                );
            }
        }
    }
}

// ---------------------------------------------------------------------------
// T-OCR-002: Pdfium fallback extracts text from all 3 PDFs
// ---------------------------------------------------------------------------

/// T-OCR-002: Verifies that the pdfium backend successfully extracts text
/// from all three OCR test PDFs when called directly. These PDFs have
/// broken cross-reference tables, malformed CID-range entries, or corrupt
/// Type1 font data that pdf-extract cannot handle, but pdfium's Chrome-
/// derived PDF engine parses correctly.
///
/// This test requires pdfium.dll / libpdfium.so at runtime. If the library
/// is not available, the test fails with a descriptive assertion message.
#[test]
fn t_ocr_002_pdfium_fallback_extracts_text() {
    assert!(
        is_pdfium_available(),
        "pdfium library is required for this test. Install pdfium via the Doctor panel.",
    );

    let paths = match ocr_pdf_paths() {
        Some(p) => p,
        None => {
            eprintln!("skipping: OCR test PDFs not found. Run: cargo run -p neuroncite-testgen");
            return;
        }
    };
    let mut files_with_text = 0_usize;

    for pdf_path in &paths {
        let result = extract_with_timeout_and_backend(pdf_path, EXTRACT_TIMEOUT, Some("pdfium"));

        match result {
            Some(pages) => {
                let total_non_ws: usize = pages
                    .iter()
                    .map(|p| p.content.chars().filter(|c| !c.is_whitespace()).count())
                    .sum();

                eprintln!(
                    "  pdfium: {} pages, {} non-ws chars for {}",
                    pages.len(),
                    total_non_ws,
                    pdf_path.file_name().unwrap_or_default().to_string_lossy()
                );

                assert!(
                    !pages.is_empty(),
                    "pdfium must return at least one page for {}",
                    pdf_path.display()
                );

                // Verify backend annotation is Pdfium for all pages.
                for page in &pages {
                    assert_eq!(
                        page.backend,
                        ExtractionBackend::Pdfium,
                        "backend must be Pdfium for page {} of {}",
                        page.page_number,
                        pdf_path.display()
                    );
                }

                if has_substantial_text(&pages, 100) {
                    files_with_text += 1;
                }
            }
            None => {
                eprintln!(
                    "  pdfium extraction failed for {}",
                    pdf_path.file_name().unwrap_or_default().to_string_lossy()
                );
            }
        }
    }

    assert!(
        files_with_text >= 2,
        "pdfium must extract substantial text from at least 2 of 3 OCR PDFs, got {files_with_text}"
    );
}

// ---------------------------------------------------------------------------
// T-OCR-003: Auto-extract fallback chain produces text for all 3 PDFs
// ---------------------------------------------------------------------------

/// T-OCR-003: Verifies that `extract_pages(path, None, None)` (the automatic
/// fallback chain: pdf-extract -> pdfium -> OCR) produces text for all three
/// OCR test PDFs. The automatic chain should use pdfium as fallback when
/// pdf-extract fails or produces low-quality text.
///
/// Requires pdfium.dll / libpdfium.so at runtime.
#[test]
fn t_ocr_003_auto_extract_fallback_chain() {
    assert!(
        is_pdfium_available(),
        "pdfium library is required for this test. Install pdfium via the Doctor panel.",
    );

    let paths = match ocr_pdf_paths() {
        Some(p) => p,
        None => {
            eprintln!("skipping: OCR test PDFs not found. Run: cargo run -p neuroncite-testgen");
            return;
        }
    };
    let mut files_with_text = 0_usize;

    for pdf_path in &paths {
        let result = extract_with_timeout_and_backend(
            pdf_path,
            EXTRACT_TIMEOUT,
            None, // auto mode
        );

        match result {
            Some(pages) => {
                let total_non_ws: usize = pages
                    .iter()
                    .map(|p| p.content.chars().filter(|c| !c.is_whitespace()).count())
                    .sum();

                eprintln!(
                    "  auto: {} pages, {} non-ws chars, backends: {:?} for {}",
                    pages.len(),
                    total_non_ws,
                    pages.iter().map(|p| &p.backend).collect::<Vec<_>>(),
                    pdf_path.file_name().unwrap_or_default().to_string_lossy()
                );

                if has_substantial_text(&pages, 100) {
                    files_with_text += 1;
                }
            }
            None => {
                eprintln!(
                    "  auto extraction failed for {}",
                    pdf_path.file_name().unwrap_or_default().to_string_lossy()
                );
            }
        }
    }

    assert!(
        files_with_text >= 2,
        "auto-extract must produce substantial text for at least 2 of 3 OCR PDFs, \
         got {files_with_text}"
    );
}

// ---------------------------------------------------------------------------
// T-OCR-004: Extracted text passes quality heuristics
// ---------------------------------------------------------------------------

/// T-OCR-004: Verifies that the text extracted via the pdfium backend passes
/// the quality heuristics defined in neuroncite_pdf::quality. For each PDF
/// where pdfium extraction succeeds, at least 50% of pages with non-trivial
/// text content must pass all quality thresholds (alphabetic ratio,
/// replacement char ratio, line break density, unique token ratio).
///
/// Requires pdfium.dll / libpdfium.so at runtime.
#[test]
fn t_ocr_004_pdfium_text_passes_quality_checks() {
    assert!(
        is_pdfium_available(),
        "pdfium library is required for this test. Install pdfium via the Doctor panel.",
    );

    let paths = match ocr_pdf_paths() {
        Some(p) => p,
        None => {
            eprintln!("skipping: OCR test PDFs not found. Run: cargo run -p neuroncite-testgen");
            return;
        }
    };
    let mut files_checked = 0_usize;

    for pdf_path in &paths {
        let pages =
            match extract_with_timeout_and_backend(pdf_path, EXTRACT_TIMEOUT, Some("pdfium")) {
                Some(p) => p,
                None => continue,
            };

        // Only check pages that have non-trivial content (>20 chars).
        let non_trivial_pages: Vec<&PageText> = pages
            .iter()
            .filter(|p| p.content.chars().filter(|c| !c.is_whitespace()).count() > 20)
            .collect();

        if non_trivial_pages.is_empty() {
            continue;
        }

        let passing_pages = non_trivial_pages
            .iter()
            .filter(|p| {
                let quality = neuroncite_pdf::quality::check_text_quality(&p.content);
                !neuroncite_pdf::quality::should_fallback(&quality)
            })
            .count();

        let pass_rate = passing_pages as f64 / non_trivial_pages.len() as f64;

        eprintln!(
            "  quality: {}/{} pages pass ({:.0}%) for {}",
            passing_pages,
            non_trivial_pages.len(),
            pass_rate * 100.0,
            pdf_path.file_name().unwrap_or_default().to_string_lossy()
        );

        assert!(
            pass_rate >= 0.50,
            "at least 50% of non-trivial pages must pass quality checks for {}, \
             got {:.0}% ({}/{})",
            pdf_path.display(),
            pass_rate * 100.0,
            passing_pages,
            non_trivial_pages.len()
        );

        files_checked += 1;
    }

    assert!(
        files_checked >= 1,
        "at least 1 OCR PDF must be checked for text quality"
    );
}

// ---------------------------------------------------------------------------
// T-OCR-005: Full pipeline with OCR PDFs stores chunks in SQLite
// ---------------------------------------------------------------------------

/// T-OCR-005: Exercises the complete indexing pipeline (extract -> chunk ->
/// store) against the OCR test PDFs using the pdfium fallback. Verifies that
/// files, pages, and chunks are persisted in SQLite with correct metadata.
///
/// Requires pdfium.dll / libpdfium.so at runtime.
#[test]
fn t_ocr_005_full_pipeline_with_ocr_pdfs() {
    assert!(
        is_pdfium_available(),
        "pdfium library is required for this test. Install pdfium via the Doctor panel.",
    );

    let dir = match ocr_pdf_dir() {
        Some(d) => d,
        None => {
            eprintln!(
                "skipping: OCR test PDF directory not found. Run: cargo run -p neuroncite-testgen"
            );
            return;
        }
    };
    let paths = match ocr_pdf_paths() {
        Some(p) => p,
        None => {
            eprintln!("skipping: OCR test PDFs not found. Run: cargo run -p neuroncite-testgen");
            return;
        }
    };

    let pool = common::create_default_test_pool();
    let conn = pool.get().expect("failed to obtain connection");
    let config = ocr_test_config(&dir);

    let session_id =
        store::create_session(&conn, &config, "0.1.0").expect("session creation failed");

    let strategy = neuroncite_chunk::create_strategy("word", Some(300), Some(50), None, None)
        .expect("strategy creation failed");

    let mut total_files_indexed = 0_usize;
    let mut total_chunks_stored = 0_usize;
    let mut total_pages_extracted = 0_usize;

    for pdf_path in &paths {
        // Use auto mode so the fallback chain engages.
        let pages = match extract_with_timeout_and_backend(pdf_path, EXTRACT_TIMEOUT, None) {
            Some(p) if has_substantial_text(&p, 50) => p,
            _ => continue,
        };

        let chunks = match strategy.chunk(&pages) {
            Ok(c) if !c.is_empty() => c,
            Ok(_) => continue,
            Err(e) => {
                eprintln!("  chunking failed for {}: {e}", pdf_path.display());
                continue;
            }
        };

        total_pages_extracted += pages.len();

        let file_hash = Chunk::compute_content_hash(
            &pages
                .iter()
                .map(|p| p.content.as_str())
                .collect::<Vec<_>>()
                .join(""),
        );

        let file_id = store::insert_file(
            &conn,
            session_id,
            &pdf_path.to_string_lossy(),
            &file_hash,
            1_700_000_000,
            std::fs::metadata(pdf_path)
                .map(|m| m.len() as i64)
                .unwrap_or(0),
            pages.len() as i64,
            None,
        )
        .expect("file insert failed");

        let pages_data: Vec<(i64, &str, &str)> = pages
            .iter()
            .map(|p| {
                (
                    p.page_number as i64,
                    p.content.as_str(),
                    match p.backend {
                        ExtractionBackend::PdfExtract => "pdf-extract",
                        ExtractionBackend::Pdfium => "pdfium",
                        ExtractionBackend::Ocr => "ocr",
                        ExtractionBackend::HtmlRaw => "html-raw",
                        ExtractionBackend::HtmlReadability => "html-readability",
                    },
                )
            })
            .collect();
        store::bulk_insert_pages(&conn, file_id, &pages_data).expect("page insert failed");

        let stub_embedding: Vec<u8> = vec![0u8; 16];
        let chunk_inserts: Vec<ChunkInsert<'_>> = chunks
            .iter()
            .map(|c| ChunkInsert {
                file_id,
                session_id,
                page_start: c.page_start as i64,
                page_end: c.page_end as i64,
                chunk_index: c.chunk_index as i64,
                doc_text_offset_start: c.doc_text_offset_start as i64,
                doc_text_offset_end: c.doc_text_offset_end as i64,
                content: &c.content,
                embedding: Some(stub_embedding.as_slice()),
                ext_offset: None,
                ext_length: None,
                content_hash: &c.content_hash,
                simhash: None,
            })
            .collect();

        let ids = store::bulk_insert_chunks(&conn, &chunk_inserts).expect("chunk insert failed");
        total_chunks_stored += ids.len();
        total_files_indexed += 1;
    }

    assert!(
        total_files_indexed >= 1,
        "at least 1 OCR PDF must be successfully indexed"
    );
    assert!(
        total_chunks_stored >= 1,
        "at least 1 chunk must be stored from OCR PDFs"
    );
    assert!(
        total_pages_extracted >= 1,
        "at least 1 page must be extracted from OCR PDFs"
    );

    // Verify database consistency.
    let files = store::list_files_by_session(&conn, session_id).expect("file listing failed");
    assert_eq!(files.len(), total_files_indexed);

    let all_chunks =
        store::list_chunks_by_session(&conn, session_id).expect("chunk listing failed");
    assert_eq!(all_chunks.len(), total_chunks_stored);

    eprintln!(
        "OCR pipeline: {total_files_indexed} files, \
         {total_pages_extracted} pages, {total_chunks_stored} chunks"
    );
}

// ---------------------------------------------------------------------------
// T-OCR-006: FTS5 keyword search finds domain terms in OCR content
// ---------------------------------------------------------------------------

/// T-OCR-006: Verifies that after indexing OCR-extracted content, the FTS5
/// full-text search index returns results for domain-specific terms that
/// are expected to appear in the three OCR test PDFs (statistics, finance,
/// and forecasting papers).
///
/// Requires pdfium.dll / libpdfium.so at runtime.
#[test]
fn t_ocr_006_fts5_search_on_ocr_content() {
    assert!(
        is_pdfium_available(),
        "pdfium library is required for this test. Install pdfium via the Doctor panel.",
    );

    let dir = match ocr_pdf_dir() {
        Some(d) => d,
        None => {
            eprintln!(
                "skipping: OCR test PDF directory not found. Run: cargo run -p neuroncite-testgen"
            );
            return;
        }
    };
    let paths = match ocr_pdf_paths() {
        Some(p) => p,
        None => {
            eprintln!("skipping: OCR test PDFs not found. Run: cargo run -p neuroncite-testgen");
            return;
        }
    };

    let pool = common::create_default_test_pool();
    let conn = pool.get().expect("failed to obtain connection");
    let config = ocr_test_config(&dir);

    let session_id =
        store::create_session(&conn, &config, "0.1.0").expect("session creation failed");

    let strategy = neuroncite_chunk::create_strategy("word", Some(300), Some(50), None, None)
        .expect("strategy creation failed");

    let mut indexed = 0_usize;

    for pdf_path in &paths {
        let pages = match extract_with_timeout_and_backend(pdf_path, EXTRACT_TIMEOUT, None) {
            Some(p) if has_substantial_text(&p, 50) => p,
            _ => continue,
        };

        let chunks = match strategy.chunk(&pages) {
            Ok(c) if !c.is_empty() => c,
            _ => continue,
        };

        let file_hash = Chunk::compute_content_hash("ocr-fts5-test");
        let file_id = store::insert_file(
            &conn,
            session_id,
            &pdf_path.to_string_lossy(),
            &file_hash,
            1_700_000_000,
            0,
            pages.len() as i64,
            None,
        )
        .expect("file insert failed");

        let pages_data: Vec<(i64, &str, &str)> = pages
            .iter()
            .map(|p| (p.page_number as i64, p.content.as_str(), "pdfium"))
            .collect();
        store::bulk_insert_pages(&conn, file_id, &pages_data).expect("page insert failed");

        let stub_emb: Vec<u8> = vec![0u8; 16];
        let chunk_inserts: Vec<ChunkInsert<'_>> = chunks
            .iter()
            .map(|c| ChunkInsert {
                file_id,
                session_id,
                page_start: c.page_start as i64,
                page_end: c.page_end as i64,
                chunk_index: c.chunk_index as i64,
                doc_text_offset_start: c.doc_text_offset_start as i64,
                doc_text_offset_end: c.doc_text_offset_end as i64,
                content: &c.content,
                embedding: Some(stub_emb.as_slice()),
                ext_offset: None,
                ext_length: None,
                content_hash: &c.content_hash,
                simhash: None,
            })
            .collect();

        store::bulk_insert_chunks(&conn, &chunk_inserts).expect("chunk insert failed");
        indexed += 1;
    }

    if indexed == 0 {
        eprintln!("no OCR PDFs produced indexable content; skipping FTS5 verification");
        return;
    }

    // Search for domain-specific terms expected in the three synthetic PDFs:
    // - XRef corruption: "statistics", "probability", "regression", "hypothesis"
    // - CID-range panic: "trading", "stock", "returns", "market"
    // - Type1 font panic: "forecast", "accuracy", "error", "mean"
    let search_terms = [
        "statistics",
        "data",
        "regression",
        "trading",
        "stock",
        "returns",
        "forecast",
        "accuracy",
        "error",
        "mean",
    ];

    let mut terms_found = 0_usize;
    for term in &search_terms {
        let count: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM chunk_fts WHERE chunk_fts MATCH ?1",
                rusqlite::params![term],
                |row| row.get(0),
            )
            .unwrap_or(0);

        if count > 0 {
            terms_found += 1;
            eprintln!("FTS5: '{term}' found in {count} chunks");
        }
    }

    assert!(
        terms_found >= 3,
        "at least 3 of {} domain terms must be found in OCR-extracted content, \
         found {terms_found}",
        search_terms.len()
    );
}

// ===========================================================================
// Targeted per-PDF regression tests
//
// Each test targets a single PDF and its specific pdf-extract failure mode.
// The tests verify three properties:
//   1. pdf-extract fails or produces unusable text for this specific PDF.
//   2. The pdfium fallback extracts meaningful text with expected domain terms.
//   3. The auto-extract chain (None backend) falls through to pdfium and
//      delivers the same quality result.
// ===========================================================================

// ---------------------------------------------------------------------------
// T-OCR-010: Synthetic xref corruption - cross-reference table error
// ---------------------------------------------------------------------------

/// T-OCR-010: The synthetic xref-corruption PDF has triple-corrupted cross-
/// reference data (xref offsets, startxref pointer, trailer /Size) that
/// causes both pdf-extract and pdfium to fail. This PDF requires OCR
/// (Tesseract) for text extraction. Without OCR, both backends fail and
/// the fallback chain correctly propagates the error.
///
/// This test verifies:
/// 1. pdf-extract fails (cross-reference error).
/// 2. pdfium also fails (FormatError from the same corruption).
/// 3. auto-extract returns an error (both backends exhausted, no OCR).
#[test]
fn t_ocr_010_cross_reference_error_openintro() {
    assert!(
        is_pdfium_available(),
        "pdfium library is required for this test. Install pdfium via the Doctor panel.",
    );

    let path = match ocr_pdf_by_problem("cross-reference-error") {
        Some(p) => p,
        None => {
            eprintln!("skipping: OCR test PDF not found. Run: cargo run -p neuroncite-testgen");
            return;
        }
    };

    // Property 1: pdf-extract fails for this PDF.
    let pdf_extract_result =
        extract_with_timeout_and_backend(&path, EXTRACT_TIMEOUT, Some("pdf-extract"));
    match pdf_extract_result {
        Some(pages) => {
            let non_ws: usize = pages
                .iter()
                .map(|p| p.content.chars().filter(|c| !c.is_whitespace()).count())
                .sum();
            assert!(
                non_ws < 500,
                "pdf-extract should produce minimal text for cross-reference-error PDF, got {non_ws} chars"
            );
        }
        None => {
            // Expected: pdf-extract returned an error.
        }
    }

    // Property 2: pdfium also fails for this PDF (FormatError due to
    // severely corrupted cross-reference table).
    let pdfium_result = extract_with_timeout_and_backend(&path, EXTRACT_TIMEOUT, Some("pdfium"));
    assert!(
        pdfium_result.is_none(),
        "pdfium should also fail for xref-corruption PDF (triple corruption \
         eliminates all repair anchor points for both backends)"
    );

    // Property 3: auto-extract returns an error because both backends fail
    // and OCR is not enabled in this build. The error should not panic.
    let auto_result = extract_with_timeout_and_backend(&path, EXTRACT_TIMEOUT, None);
    if let Some(pages) = auto_result {
        // If auto mode somehow produced pages (e.g., OCR was available),
        // they should contain meaningful text.
        let non_ws: usize = pages
            .iter()
            .map(|p| p.content.chars().filter(|c| !c.is_whitespace()).count())
            .sum();
        eprintln!(
            "auto-extract produced {non_ws} non-whitespace chars for xref-corruption PDF \
             (OCR may be available)"
        );
    } else {
        // Expected: both text backends failed, no OCR available.
        eprintln!(
            "auto-extract correctly returned error for xref-corruption PDF \
             (both backends failed, OCR not available)"
        );
    }
}

// ---------------------------------------------------------------------------
// T-OCR-011: Synthetic CID-range font table panic
// ---------------------------------------------------------------------------

/// T-OCR-011: The synthetic CID-range PDF has a malformed CMap encoding
/// stream that causes pdf-extract to panic in adobe_cmap_parser (not return
/// an error). Verifies that pdf-extract panics, pdfium succeeds, and the
/// extracted Helvetica text contains finance terms ("trading", "stock", "returns").
#[test]
fn t_ocr_011_cid_range_panic_brock() {
    assert!(
        is_pdfium_available(),
        "pdfium library is required for this test. Install pdfium via the Doctor panel.",
    );

    let path = match ocr_pdf_by_problem("cid-range-panic") {
        Some(p) => p,
        None => {
            eprintln!("skipping: OCR test PDF not found. Run: cargo run -p neuroncite-testgen");
            return;
        }
    };

    // Property 1: pdf-extract panics or fails for this PDF.
    let pdf_extract_result =
        extract_with_timeout_and_backend(&path, EXTRACT_TIMEOUT, Some("pdf-extract"));
    match pdf_extract_result {
        Some(pages) => {
            let non_ws: usize = pages
                .iter()
                .map(|p| p.content.chars().filter(|c| !c.is_whitespace()).count())
                .sum();
            assert!(
                non_ws < 500,
                "pdf-extract should produce minimal text for cid-range-panic PDF, got {non_ws} chars"
            );
        }
        None => {
            // Expected: pdf-extract panicked in the CID-range parser.
        }
    }

    // Property 2: pdfium extracts meaningful text with finance domain terms.
    let pdfium_pages = extract_with_timeout_and_backend(&path, EXTRACT_TIMEOUT, Some("pdfium"))
        .expect("pdfium must succeed for cid-range-panic PDF");

    assert!(
        !pdfium_pages.is_empty(),
        "pdfium must return pages for CID-range panic PDF"
    );

    let all_text: String = pdfium_pages.iter().map(|p| p.content.as_str()).collect();
    let all_text_lower = all_text.to_lowercase();

    // CID-range PDF covers technical trading rules, stock returns, market.
    let expected_terms = ["trading", "stock", "return"];
    let mut found = 0;
    for term in &expected_terms {
        if all_text_lower.contains(term) {
            found += 1;
        }
    }
    assert!(
        found >= 2,
        "pdfium text from CID-range PDF must contain at least 2 of {:?}, found {found}",
        expected_terms
    );

    for page in &pdfium_pages {
        assert_eq!(page.backend, ExtractionBackend::Pdfium);
    }

    // Property 3: auto mode delivers text via the fallback chain.
    let auto_pages = extract_with_timeout_and_backend(&path, EXTRACT_TIMEOUT, None)
        .expect("auto-extract must succeed for cid-range-panic PDF");
    assert!(
        has_substantial_text(&auto_pages, 200),
        "auto-extract must produce substantial text for CID-range panic PDF"
    );
}

// ---------------------------------------------------------------------------
// T-OCR-012: Synthetic Type1 font encoding panic
// ---------------------------------------------------------------------------

/// T-OCR-012: The synthetic Type1 PDF has a malformed FontFile stream with
/// an unterminated PostScript string literal that causes pdf-extract to panic
/// in type1_encoding_parser. Verifies that pdfium succeeds and the extracted
/// Helvetica text contains forecasting terms ("forecast", "accuracy", "error").
#[test]
fn t_ocr_012_type1_font_panic_hyndman() {
    assert!(
        is_pdfium_available(),
        "pdfium library is required for this test. Install pdfium via the Doctor panel.",
    );

    let path = match ocr_pdf_by_problem("type1-font-panic") {
        Some(p) => p,
        None => {
            eprintln!("skipping: OCR test PDF not found. Run: cargo run -p neuroncite-testgen");
            return;
        }
    };

    // Property 1: pdf-extract either panics on the Type1 font encoding or
    // (since pdf-extract 0.7.12) successfully extracts text. Both outcomes
    // are acceptable; the critical requirement is that auto-mode handles
    // this PDF without crashing.
    let _pdf_extract_result =
        extract_with_timeout_and_backend(&path, EXTRACT_TIMEOUT, Some("pdf-extract"));

    // Property 2: pdfium extracts meaningful text with forecasting domain terms.
    let pdfium_pages = extract_with_timeout_and_backend(&path, EXTRACT_TIMEOUT, Some("pdfium"))
        .expect("pdfium must succeed for type1-font-panic PDF");

    assert!(
        !pdfium_pages.is_empty(),
        "pdfium must return pages for Type1 font panic PDF"
    );

    let all_text: String = pdfium_pages.iter().map(|p| p.content.as_str()).collect();
    let all_text_lower = all_text.to_lowercase();

    // Type1 font panic PDF covers forecast accuracy measures (MAPE, MAE, etc.).
    let expected_terms = ["forecast", "accuracy", "error"];
    let mut found = 0;
    for term in &expected_terms {
        if all_text_lower.contains(term) {
            found += 1;
        }
    }
    assert!(
        found >= 2,
        "pdfium text from Type1 font panic PDF must contain at least 2 of {:?}, found {found}",
        expected_terms
    );

    for page in &pdfium_pages {
        assert_eq!(page.backend, ExtractionBackend::Pdfium);
    }

    // Property 3: auto mode delivers text via the fallback chain.
    let auto_pages = extract_with_timeout_and_backend(&path, EXTRACT_TIMEOUT, None)
        .expect("auto-extract must succeed for type1-font-panic PDF");
    assert!(
        has_substantial_text(&auto_pages, 200),
        "auto-extract must produce substantial text for Type1 font panic PDF"
    );
}

// ---------------------------------------------------------------------------
// T-OCR-013: Auto-extract produces pages with recognized backends
// ---------------------------------------------------------------------------

/// T-OCR-013: Verifies that the auto-extract chain (backend=None) produces
/// non-empty pages for all three problematic PDFs and that every page is
/// annotated with a recognized backend (PdfExtract, Pdfium, or Ocr). Mixed
/// backends within a single file are expected because the per-page quality
/// checks route pages individually through the fallback chain.
#[test]
fn t_ocr_013_auto_extract_uses_pdfium_backend() {
    assert!(
        is_pdfium_available(),
        "pdfium library is required for this test. Install pdfium via the Doctor panel.",
    );

    let paths = match ocr_pdf_paths() {
        Some(p) => p,
        None => {
            eprintln!("skipping: OCR test PDFs not found. Run: cargo run -p neuroncite-testgen");
            return;
        }
    };
    let mut files_checked = 0_usize;

    for pdf_path in &paths {
        let pages = match extract_with_timeout_and_backend(pdf_path, EXTRACT_TIMEOUT, None) {
            Some(p) if !p.is_empty() => p,
            _ => continue,
        };

        // Every page must have been extracted by a recognized backend
        // (PdfExtract, Pdfium, or Ocr). Mixed backends within a single
        // file are valid because the auto-extract chain applies per-page
        // quality checks: pages with sufficient embedded text keep their
        // PdfExtract or Pdfium backend, while pages with sparse text fall
        // through to OCR. This per-page fallback produces higher overall
        // text quality than forcing a single backend for the entire file.
        for page in &pages {
            assert!(
                matches!(
                    page.backend,
                    ExtractionBackend::PdfExtract
                        | ExtractionBackend::Pdfium
                        | ExtractionBackend::Ocr
                ),
                "page {} of {} has unexpected backend {:?}",
                page.page_number,
                pdf_path.file_name().unwrap_or_default().to_string_lossy(),
                page.backend
            );
        }

        files_checked += 1;
    }

    assert!(
        files_checked >= 2,
        "at least 2 of 3 problematic PDFs must be verified, got {files_checked}"
    );
}

// ---------------------------------------------------------------------------
// T-OCR-020: Tesseract CLI OCR produces text from a rendered page
// ---------------------------------------------------------------------------

/// T-OCR-020: Verifies that the Tesseract CLI subprocess OCR pipeline works
/// end-to-end. Creates a minimal PNG image containing a white pixel, invokes
/// `neuroncite_pdf::ocr::ocr_page()` which writes the image to a temp file
/// and calls `tesseract <file> stdout -l eng`, and checks the result.
///
/// Tesseract must be installed (on PATH or in the NeuronCite runtime cache)
/// for this test to pass. If Tesseract is missing, the test fails with a
/// descriptive error message directing the user to install it.
///
/// Requires the `ocr` feature to be enabled.
#[cfg(feature = "ocr")]
#[test]
fn t_ocr_020_tesseract_cli_ocr_produces_text() {
    // Valid 1x1 white RGB PNG image generated with correct zlib compression
    // and CRC checksums. The raw pixel row is: filter=0x00, R=0xFF, G=0xFF,
    // B=0xFF, zlib-compressed with default compression level.
    let minimal_png: &[u8] = &[
        0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // PNG signature
        0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52, // IHDR chunk (13 bytes)
        0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, // width=1, height=1
        0x08, 0x02, 0x00, 0x00, 0x00, 0x90, 0x77, 0x53, // 8-bit RGB + CRC
        0xDE, 0x00, 0x00, 0x00, 0x0C, 0x49, 0x44, 0x41, // IDAT chunk (12 bytes)
        0x54, 0x78, 0x9C, 0x63, 0xF8, 0xFF, 0xFF, 0x3F, // zlib data
        0x00, 0x05, 0xFE, 0x02, 0xFE, 0x0D, 0xEF, 0x46, // adler32 + CRC
        0xB8, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, // IEND chunk
        0x44, 0xAE, 0x42, 0x60, 0x82, // IEND CRC
    ];

    let result = neuroncite_pdf::ocr::ocr_page(minimal_png, "eng");

    // Skip the test when Tesseract is not installed. On CI runners, Tesseract
    // may not be available, and this test verifies the OCR pipeline rather than
    // testing Tesseract installation. The DepDownload error variant indicates
    // Tesseract is missing from PATH and from the runtime cache.
    let text = match result {
        Ok(t) => t,
        Err(ref e) if format!("{e:?}").contains("DepDownload") => {
            eprintln!("T-OCR-020: skipping -- Tesseract not installed");
            return;
        }
        Err(e) => panic!("OCR failed with unexpected error: {e:?}"),
    };

    // A 1x1 white pixel produces empty or whitespace-only OCR output.
    eprintln!(
        "T-OCR-022: Tesseract CLI returned {} bytes of text",
        text.len()
    );
    assert!(
        text.trim().is_empty() || text.len() < 100,
        "OCR of a single white pixel should produce minimal text, got {} bytes",
        text.len()
    );
}

// ---------------------------------------------------------------------------
// T-OCR-021: Batch OCR on a real PDF via the auto-extract fallback chain
// ---------------------------------------------------------------------------

/// T-OCR-021: Uses one of the two PDFs that pdfium can open (CID-range PDF)
/// and verifies that when the OCR feature is enabled, the auto-extract
/// fallback chain completes without crashing. Since the CID-range PDF PDF
/// contains embedded text (not scanned images), pdfium extracts text directly
/// and the OCR path is reached only for pages with sparse text. The primary
/// assertion is that extraction succeeds and produces substantial text.
///
/// Requires pdfium and Tesseract at runtime.
#[cfg(feature = "ocr")]
#[test]
fn t_ocr_021_batch_ocr_on_real_pdf() {
    assert!(
        is_pdfium_available(),
        "pdfium library is required for this test. Install pdfium via the Doctor panel.",
    );

    // Use the CID-range PDF PDF (CID-range panic in pdf-extract, pdfium succeeds).
    let path = match ocr_pdf_by_problem("cid-range-panic") {
        Some(p) => p,
        None => {
            eprintln!("skipping: OCR test PDF not found. Run: cargo run -p neuroncite-testgen");
            return;
        }
    };

    // Extract with auto mode (fallback chain: pdf-extract -> pdfium -> OCR).
    let result = extract_with_timeout_and_backend(&path, EXTRACT_TIMEOUT, None);

    match result {
        Some(pages) => {
            assert!(
                !pages.is_empty(),
                "auto-extract must return pages for CID-range PDF"
            );

            // Count pages by backend to verify code path coverage.
            let mut backend_counts = std::collections::HashMap::new();
            for page in &pages {
                *backend_counts
                    .entry(format!("{:?}", page.backend))
                    .or_insert(0_usize) += 1;
            }

            eprintln!(
                "T-OCR-023: {} pages extracted, backends: {:?}",
                pages.len(),
                backend_counts
            );

            assert!(
                has_substantial_text(&pages, 100),
                "auto-extract must produce substantial text for CID-range PDF"
            );
        }
        None => {
            eprintln!("T-OCR-024: extraction failed (may need Tesseract for OCR fallback)");
        }
    }
}
