// NeuronCite -- local, privacy-preserving semantic document search engine.
// Copyright (C) 2026 NeuronCite Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Integration tests using the synthetic PDF fixtures from neuroncite-testgen.
//
// This module exercises the complete indexing pipeline against the synthetic
// test PDFs in tests/PDFs/ocr/: PDF discovery, text extraction (with
// fallback for malformed fonts), word-window chunking, sentence chunking,
// page-based chunking, SQLite storage with FTS5 population, and HNSW
// index construction.
//
// The synthetic PDFs replace the copyrighted academic papers that were
// previously used. Two of the three synthetic PDFs (CID-range and Type1)
// contain extractable Helvetica text; the third (xref-corruption) is
// intentionally unreadable by both pdf-extract and pdfium.
//
// Every call to `extract_pages` is wrapped in `extract_with_timeout`,
// which runs extraction in a dedicated thread with a per-file timeout.
// This prevents the test suite from hanging when the third-party
// `pdf-extract` crate enters an infinite loop on certain font encodings.
//
// All tests in this module acquire `common::acquire_heavy_test_lock()`
// at entry. This serializes execution so that at most one pipeline test
// runs at a time.

use std::path::{Path, PathBuf};
use std::sync::mpsc;
use std::time::Duration;

use neuroncite_core::{
    Chunk, ChunkStrategy, EmbeddingBackend, ExtractionBackend, IndexConfig, PageText, StorageMode,
};
use neuroncite_store::{self as store, ChunkInsert};

use crate::common;

/// Per-file timeout for PDF text extraction. If a single PDF takes longer
/// than this to extract, it is skipped.
const EXTRACT_TIMEOUT: Duration = Duration::from_secs(30);

// ---------------------------------------------------------------------------
// Helper: resolve the synthetic PDF test directory
// ---------------------------------------------------------------------------

/// Returns the absolute path to the `tests/PDFs/ocr/` directory containing
/// the synthetic test PDFs generated by neuroncite-testgen. The path is
/// resolved relative to the neuroncite binary crate's manifest directory.
///
/// Returns `None` if the directory does not exist (PDFs not yet generated).
fn synthetic_pdf_dir() -> Option<PathBuf> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("failed to resolve workspace root from CARGO_MANIFEST_DIR");
    let pdf_dir = workspace_root.join("tests").join("PDFs").join("ocr");
    if pdf_dir.is_dir() {
        Some(pdf_dir)
    } else {
        None
    }
}

/// Returns an IndexConfig suitable for pipeline tests with word-window
/// chunking (300 words, 50 overlap).
fn pipeline_config(directory: &Path) -> IndexConfig {
    IndexConfig {
        directory: directory.to_path_buf(),
        model_name: "stub-model".to_string(),
        chunk_strategy: "word".to_string(),
        chunk_size: Some(300),
        chunk_overlap: Some(50),
        max_words: None,
        ocr_language: "eng".to_string(),
        embedding_storage_mode: StorageMode::SqliteBlob,
        vector_dimension: 4,
    }
}

/// Extracts pages from a PDF file with a per-file timeout. Runs the
/// extraction in a separate thread and uses a channel with `recv_timeout`
/// to enforce the deadline. Catches panics from the third-party
/// `pdf-extract` crate's font parser that occur on malformed font encodings.
///
/// Returns `Some(pages)` on success, `None` on extraction failure, panic,
/// or timeout.
fn extract_with_timeout(pdf_path: &Path, timeout: Duration) -> Option<Vec<PageText>> {
    let path = pdf_path.to_path_buf();
    let (tx, rx) = mpsc::channel();

    // Use 8 MB stack to accommodate pdfium FFI C-library call frames during
    // PDF font parsing (CID-range, Type1).
    std::thread::Builder::new()
        .stack_size(8 * 1024 * 1024)
        .spawn(move || {
            let result =
                std::panic::catch_unwind(move || neuroncite_pdf::extract_pages(&path, None, None));
            let _ = tx.send(result);
        })
        .expect("failed to spawn extraction thread");

    match rx.recv_timeout(timeout) {
        Ok(Ok(Ok(extraction))) => Some(extraction.pages),
        Ok(Ok(Err(e))) => {
            eprintln!("  extraction error for {}: {e}", pdf_path.display());
            None
        }
        Ok(Err(_)) => {
            eprintln!(
                "  extraction panicked for {} (third-party font parser)",
                pdf_path.display()
            );
            None
        }
        Err(_) => {
            eprintln!(
                "  extraction timed out for {} after {timeout:?}",
                pdf_path.display()
            );
            None
        }
    }
}

/// Returns true if the page list contains at least one page with more
/// than `min_chars` non-whitespace characters.
fn has_substantial_text(pages: &[PageText], min_chars: usize) -> bool {
    pages
        .iter()
        .any(|p| p.content.chars().filter(|c| !c.is_whitespace()).count() > min_chars)
}

/// Result of parallel extraction and chunking of a single PDF file.
struct ExtractedFile {
    pdf_path: PathBuf,
    pages: Vec<PageText>,
    chunks: Vec<neuroncite_core::Chunk>,
}

/// Extracts and chunks a single PDF file. Uses `extract_with_timeout` for
/// panic and timeout protection, then applies the chunking strategy.
fn extract_and_chunk(pdf_path: &Path, strategy: &dyn ChunkStrategy) -> Option<ExtractedFile> {
    let pages = extract_with_timeout(pdf_path, EXTRACT_TIMEOUT)?;

    if !has_substantial_text(&pages, 50) {
        return None;
    }

    let chunks = match strategy.chunk(&pages) {
        Ok(c) if !c.is_empty() => c,
        Ok(_) => return None,
        Err(e) => {
            eprintln!("  chunking failed for {}: {e}", pdf_path.display());
            return None;
        }
    };

    Some(ExtractedFile {
        pdf_path: pdf_path.to_path_buf(),
        pages,
        chunks,
    })
}

// ---------------------------------------------------------------------------
// T-REAL-001: Discovery finds PDF files in the synthetic test directory
// ---------------------------------------------------------------------------

/// T-REAL-001: Verifies that neuroncite_pdf::discover_pdfs correctly locates
/// PDF files in the synthetic test directory (tests/PDFs/ocr/ with 3
/// subdirectories, each containing one synthetic PDF).
#[test]
fn t_real_001_discover_all_real_pdfs() {
    let _lock = common::acquire_heavy_test_lock();
    let pdf_dir = match synthetic_pdf_dir() {
        Some(d) => d,
        None => {
            eprintln!(
                "skipping: synthetic PDF directory not found. Run: cargo run -p neuroncite-testgen"
            );
            return;
        }
    };

    let discovered = neuroncite_pdf::discover_pdfs(&pdf_dir)
        .expect("PDF discovery must succeed on the synthetic test directory");

    assert!(
        discovered.len() >= 3,
        "test directory must contain at least 3 synthetic PDF files, found {}",
        discovered.len()
    );

    for path in &discovered {
        assert!(
            path.exists(),
            "discovered PDF path must exist: {}",
            path.display()
        );
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        assert_eq!(
            ext.to_lowercase(),
            "pdf",
            "must have .pdf extension: {}",
            path.display()
        );
    }
}

// ---------------------------------------------------------------------------
// T-REAL-002: Text extraction succeeds for at least some synthetic PDFs
// ---------------------------------------------------------------------------

/// T-REAL-002: Verifies that text extraction produces non-empty page content
/// for at least one synthetic PDF. The auto-fallback chain (pdf-extract ->
/// pdfium -> OCR) handles the malformed fonts in the CID-range and Type1
/// fixtures.
#[test]
fn t_real_002_text_extraction_from_clean_pdfs() {
    let _lock = common::acquire_heavy_test_lock();
    let pdf_dir = match synthetic_pdf_dir() {
        Some(d) => d,
        None => {
            eprintln!("skipping: synthetic PDF directory not found");
            return;
        }
    };
    let discovered = neuroncite_pdf::discover_pdfs(&pdf_dir).expect("PDF discovery failed");

    let results: Vec<(PathBuf, Vec<PageText>)> = discovered
        .iter()
        .filter_map(|pdf_path| {
            let pages = extract_with_timeout(pdf_path, EXTRACT_TIMEOUT)?;
            Some((pdf_path.clone(), pages))
        })
        .collect();

    let files_with_text = results
        .iter()
        .filter(|(_, pages)| has_substantial_text(pages, 50))
        .count();

    assert!(
        files_with_text > 0,
        "at least one synthetic PDF must contain substantial text content"
    );
}

// ---------------------------------------------------------------------------
// T-REAL-003: Malformed PDFs handled gracefully
// ---------------------------------------------------------------------------

/// T-REAL-003: Verifies that the synthetic PDFs with malformed fonts are
/// handled without panics or hangs. Each PDF is extracted sequentially with
/// per-file timeout protection. Each file is classified by text density.
#[test]
fn t_real_003_scanned_pdfs_handled_gracefully() {
    let _lock = common::acquire_heavy_test_lock();
    let pdf_dir = match synthetic_pdf_dir() {
        Some(d) => d,
        None => {
            eprintln!("skipping: synthetic PDF directory not found");
            return;
        }
    };
    let discovered = neuroncite_pdf::discover_pdfs(&pdf_dir).expect("PDF discovery failed");

    enum PdfClass {
        Text,
        Scanned,
        Error,
    }

    let classes: Vec<PdfClass> = discovered
        .iter()
        .map(
            |pdf_path| match extract_with_timeout(pdf_path, EXTRACT_TIMEOUT) {
                Some(pages) => {
                    let all_sparse = pages
                        .iter()
                        .all(|p| p.content.chars().filter(|c| !c.is_whitespace()).count() < 20);
                    if pages.is_empty() || all_sparse {
                        PdfClass::Scanned
                    } else {
                        PdfClass::Text
                    }
                }
                None => PdfClass::Error,
            },
        )
        .collect();

    let text_count = classes
        .iter()
        .filter(|c| matches!(c, PdfClass::Text))
        .count();
    let scanned_count = classes
        .iter()
        .filter(|c| matches!(c, PdfClass::Scanned))
        .count();
    let error_count = classes
        .iter()
        .filter(|c| matches!(c, PdfClass::Error))
        .count();

    eprintln!(
        "PDF classification: text={text_count}, scanned={scanned_count}, errors={error_count}"
    );

    // The xref-corruption PDF causes extraction errors; the CID-range and
    // Type1 PDFs produce text via the pdfium fallback. At least one must
    // yield text.
    assert!(
        text_count + error_count > 0,
        "at least one PDF must be processed (text or graceful error)"
    );
}

// ---------------------------------------------------------------------------
// T-REAL-004: Full pipeline stores chunks in SQLite
// ---------------------------------------------------------------------------

/// T-REAL-004: Exercises the complete indexing pipeline: extract, chunk,
/// and store in SQLite. Uses the synthetic PDFs via the auto-fallback chain.
#[test]
fn t_real_004_full_pipeline_with_real_pdfs() {
    let _lock = common::acquire_heavy_test_lock();
    let pdf_dir = match synthetic_pdf_dir() {
        Some(d) => d,
        None => {
            eprintln!("skipping: synthetic PDF directory not found");
            return;
        }
    };
    let discovered = neuroncite_pdf::discover_pdfs(&pdf_dir).expect("PDF discovery failed");

    let pool = common::create_default_test_pool();
    let conn = pool.get().expect("failed to obtain connection");
    let config = pipeline_config(&pdf_dir);

    let session_id =
        store::create_session(&conn, &config, "0.1.0").expect("session creation failed");

    let strategy = neuroncite_chunk::create_strategy("word", Some(300), Some(50), None, None)
        .expect("strategy creation failed");

    let extracted: Vec<ExtractedFile> = discovered
        .iter()
        .filter_map(|pdf_path| extract_and_chunk(pdf_path, strategy.as_ref()))
        .collect();

    let mut total_files_indexed = 0_usize;
    let mut total_chunks_stored = 0_usize;
    let mut total_pages_extracted = 0_usize;

    for ef in &extracted {
        total_pages_extracted += ef.pages.len();

        let file_hash = Chunk::compute_content_hash(
            &ef.pages
                .iter()
                .map(|p| p.content.as_str())
                .collect::<Vec<_>>()
                .join(""),
        );
        let file_id = store::insert_file(
            &conn,
            session_id,
            &ef.pdf_path.to_string_lossy(),
            &file_hash,
            1_700_000_000,
            std::fs::metadata(&ef.pdf_path)
                .map(|m| m.len() as i64)
                .unwrap_or(0),
            ef.pages.len() as i64,
            None,
        )
        .expect("file insert failed");

        let pages_data: Vec<(i64, &str, &str)> = ef
            .pages
            .iter()
            .map(|p| {
                (
                    p.page_number as i64,
                    p.content.as_str(),
                    match p.backend {
                        ExtractionBackend::PdfExtract => "pdf-extract",
                        ExtractionBackend::Pdfium => "pdfium",
                        ExtractionBackend::Ocr => "ocr",
                        ExtractionBackend::HtmlRaw => "html-raw",
                        ExtractionBackend::HtmlReadability => "html-readability",
                    },
                )
            })
            .collect();
        store::bulk_insert_pages(&conn, file_id, &pages_data).expect("page insert failed");

        let stub_embedding: Vec<u8> = vec![0u8; 16];
        let chunk_inserts: Vec<ChunkInsert<'_>> = ef
            .chunks
            .iter()
            .map(|c| ChunkInsert {
                file_id,
                session_id,
                page_start: c.page_start as i64,
                page_end: c.page_end as i64,
                chunk_index: c.chunk_index as i64,
                doc_text_offset_start: c.doc_text_offset_start as i64,
                doc_text_offset_end: c.doc_text_offset_end as i64,
                content: &c.content,
                embedding: Some(stub_embedding.as_slice()),
                ext_offset: None,
                ext_length: None,
                content_hash: &c.content_hash,
                simhash: None,
            })
            .collect();

        let ids = store::bulk_insert_chunks(&conn, &chunk_inserts).expect("chunk insert failed");
        total_chunks_stored += ids.len();
        total_files_indexed += 1;
    }

    assert!(
        total_files_indexed > 0,
        "at least one synthetic PDF must be successfully indexed"
    );
    assert!(total_chunks_stored > 0, "at least one chunk must be stored");

    let files = store::list_files_by_session(&conn, session_id).expect("file listing failed");
    assert_eq!(files.len(), total_files_indexed);

    let all_chunks =
        store::list_chunks_by_session(&conn, session_id).expect("chunk listing failed");
    assert_eq!(all_chunks.len(), total_chunks_stored);

    eprintln!(
        "pipeline: {total_files_indexed} files, \
         {total_pages_extracted} pages, {total_chunks_stored} chunks"
    );
}

// ---------------------------------------------------------------------------
// T-REAL-005: FTS5 keyword search works on synthetic PDF content
// ---------------------------------------------------------------------------

/// T-REAL-005: Verifies that after indexing synthetic PDF content, the FTS5
/// full-text search index returns results for domain-specific terms present
/// in the synthetic fixtures (statistics, finance, forecasting).
#[test]
fn t_real_005_fts5_search_on_real_content() {
    let _lock = common::acquire_heavy_test_lock();
    let pdf_dir = match synthetic_pdf_dir() {
        Some(d) => d,
        None => {
            eprintln!("skipping: synthetic PDF directory not found");
            return;
        }
    };
    let discovered = neuroncite_pdf::discover_pdfs(&pdf_dir).expect("PDF discovery failed");

    let pool = common::create_default_test_pool();
    let conn = pool.get().expect("failed to obtain connection");
    let config = pipeline_config(&pdf_dir);

    let session_id =
        store::create_session(&conn, &config, "0.1.0").expect("session creation failed");

    let strategy = neuroncite_chunk::create_strategy("word", Some(300), Some(50), None, None)
        .expect("strategy creation failed");

    let extracted: Vec<ExtractedFile> = discovered
        .iter()
        .filter_map(|pdf_path| extract_and_chunk(pdf_path, strategy.as_ref()))
        .collect();

    let mut indexed = 0_usize;
    for ef in &extracted {
        let file_hash = Chunk::compute_content_hash("synthetic-pdf-content");
        let file_id = store::insert_file(
            &conn,
            session_id,
            &ef.pdf_path.to_string_lossy(),
            &file_hash,
            1_700_000_000,
            0,
            ef.pages.len() as i64,
            None,
        )
        .expect("file insert failed");

        let pages_data: Vec<(i64, &str, &str)> = ef
            .pages
            .iter()
            .map(|p| (p.page_number as i64, p.content.as_str(), "pdfium"))
            .collect();
        store::bulk_insert_pages(&conn, file_id, &pages_data).expect("page insert failed");

        let stub_emb: Vec<u8> = vec![0u8; 16];
        let chunk_inserts: Vec<ChunkInsert<'_>> = ef
            .chunks
            .iter()
            .map(|c| ChunkInsert {
                file_id,
                session_id,
                page_start: c.page_start as i64,
                page_end: c.page_end as i64,
                chunk_index: c.chunk_index as i64,
                doc_text_offset_start: c.doc_text_offset_start as i64,
                doc_text_offset_end: c.doc_text_offset_end as i64,
                content: &c.content,
                embedding: Some(stub_emb.as_slice()),
                ext_offset: None,
                ext_length: None,
                content_hash: &c.content_hash,
                simhash: None,
            })
            .collect();

        store::bulk_insert_chunks(&conn, &chunk_inserts).expect("chunk insert failed");
        indexed += 1;
    }

    assert!(
        indexed > 0,
        "at least one PDF must be indexed for FTS5 testing"
    );

    // Domain terms from the synthetic PDFs: statistics (xref), finance
    // (CID-range), and forecasting (Type1). The xref-corruption PDF text
    // is not extractable, so only finance and forecasting terms appear.
    let search_terms = [
        "trading",
        "stock",
        "returns",
        "forecast",
        "accuracy",
        "error",
        "bootstrap",
        "prediction",
    ];

    let mut terms_found = 0_usize;
    for term in &search_terms {
        let count: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM chunk_fts WHERE chunk_fts MATCH ?1",
                rusqlite::params![term],
                |row| row.get(0),
            )
            .unwrap_or(0);

        if count > 0 {
            terms_found += 1;
            eprintln!("FTS5: '{term}' found in {count} chunks");
        }
    }

    assert!(
        terms_found >= 3,
        "at least 3 of {} search terms must be found, found {terms_found}",
        search_terms.len()
    );
}

// ---------------------------------------------------------------------------
// T-REAL-007: Sentence chunking strategy works on synthetic PDF content
// ---------------------------------------------------------------------------

/// T-REAL-007: Verifies that the sentence-based chunking strategy produces
/// valid chunks from synthetic PDF content.
#[test]
fn t_real_007_sentence_chunking_on_real_content() {
    let _lock = common::acquire_heavy_test_lock();
    let pdf_dir = match synthetic_pdf_dir() {
        Some(d) => d,
        None => {
            eprintln!("skipping: synthetic PDF directory not found");
            return;
        }
    };
    let discovered = neuroncite_pdf::discover_pdfs(&pdf_dir).expect("PDF discovery failed");

    let strategy = neuroncite_chunk::create_strategy("sentence", Some(5), Some(1), Some(500), None)
        .expect("sentence strategy creation failed");

    let results: Vec<(PathBuf, Vec<neuroncite_core::Chunk>)> = discovered
        .iter()
        .filter_map(|pdf_path| {
            let pages = extract_with_timeout(pdf_path, EXTRACT_TIMEOUT)?;
            if !has_substantial_text(&pages, 100) {
                return None;
            }
            let chunks = strategy.chunk(&pages).ok()?;
            if chunks.is_empty() {
                return None;
            }
            Some((pdf_path.clone(), chunks))
        })
        .collect();

    let files_chunked = results.len();
    let total_sentence_chunks: usize = results.iter().map(|(_, c)| c.len()).sum();

    assert!(
        files_chunked > 0,
        "at least one PDF must produce sentence-based chunks"
    );
    assert!(
        total_sentence_chunks > 0,
        "sentence chunking must produce at least one chunk"
    );

    eprintln!("sentence chunking: {files_chunked} files, {total_sentence_chunks} chunks");
}

// ---------------------------------------------------------------------------
// T-REAL-008: Page-based chunking strategy works on synthetic PDF content
// ---------------------------------------------------------------------------

/// T-REAL-008: Verifies that the page-based chunking strategy produces one
/// chunk per non-empty page from synthetic PDF content.
#[test]
fn t_real_008_page_chunking_on_real_content() {
    let _lock = common::acquire_heavy_test_lock();
    let pdf_dir = match synthetic_pdf_dir() {
        Some(d) => d,
        None => {
            eprintln!("skipping: synthetic PDF directory not found");
            return;
        }
    };
    let discovered = neuroncite_pdf::discover_pdfs(&pdf_dir).expect("PDF discovery failed");

    let strategy = neuroncite_chunk::create_strategy("page", None, None, None, None)
        .expect("page strategy creation failed");

    for pdf_path in &discovered {
        let pages = match extract_with_timeout(pdf_path, EXTRACT_TIMEOUT) {
            Some(p) => p,
            None => continue,
        };

        if pages.is_empty() {
            continue;
        }

        let chunks = strategy.chunk(&pages).expect("page chunking failed");

        let non_empty_pages = pages
            .iter()
            .filter(|p| !p.content.trim().is_empty())
            .count();

        assert_eq!(
            chunks.len(),
            non_empty_pages,
            "page chunking must produce one chunk per non-empty page for {}",
            pdf_path.display()
        );

        for chunk in &chunks {
            assert!(chunk.page_start >= 1, "chunk page_start must be >= 1");
            assert_eq!(
                chunk.page_start, chunk.page_end,
                "page-based chunks must span one page"
            );
        }

        eprintln!(
            "page chunking {}: {} pages -> {} chunks",
            pdf_path.file_name().unwrap_or_default().to_string_lossy(),
            pages.len(),
            chunks.len()
        );

        break;
    }
}

// ---------------------------------------------------------------------------
// T-REAL-009: HNSW index construction from synthetic PDF embeddings
// ---------------------------------------------------------------------------

/// T-REAL-009: Verifies that an HNSW index can be built from chunk embeddings
/// produced during the indexing of synthetic PDFs. Uses stub embeddings
/// (4-dimensional).
#[test]
fn t_real_009_hnsw_from_real_pdf_chunks() {
    let _lock = common::acquire_heavy_test_lock();
    let pdf_dir = match synthetic_pdf_dir() {
        Some(d) => d,
        None => {
            eprintln!("skipping: synthetic PDF directory not found");
            return;
        }
    };
    let discovered = neuroncite_pdf::discover_pdfs(&pdf_dir).expect("PDF discovery failed");

    let pool = common::create_default_test_pool();
    let conn = pool.get().expect("failed to obtain connection");
    let config = pipeline_config(&pdf_dir);

    let session_id =
        store::create_session(&conn, &config, "0.1.0").expect("session creation failed");

    let strategy = neuroncite_chunk::create_strategy("word", Some(300), Some(50), None, None)
        .expect("strategy creation failed");

    let stub_embedder = common::StubEmbedder;

    let extracted: Vec<ExtractedFile> = discovered
        .iter()
        .filter_map(|pdf_path| extract_and_chunk(pdf_path, strategy.as_ref()))
        .collect();

    for ef in &extracted {
        let file_hash = Chunk::compute_content_hash("hnsw-test");
        let file_id = store::insert_file(
            &conn,
            session_id,
            &ef.pdf_path.to_string_lossy(),
            &file_hash,
            1_700_000_000,
            0,
            ef.pages.len() as i64,
            None,
        )
        .expect("file insert failed");

        let pages_data: Vec<(i64, &str, &str)> = ef
            .pages
            .iter()
            .map(|p| (p.page_number as i64, p.content.as_str(), "pdfium"))
            .collect();
        store::bulk_insert_pages(&conn, file_id, &pages_data).expect("page insert failed");

        let texts: Vec<&str> = ef.chunks.iter().map(|c| c.content.as_str()).collect();
        let embeddings = stub_embedder
            .embed_batch(&texts)
            .expect("stub embedding failed");

        let emb_bytes: Vec<Vec<u8>> = embeddings
            .iter()
            .map(|emb| emb.iter().flat_map(|f| f.to_le_bytes()).collect())
            .collect();

        let chunk_inserts: Vec<ChunkInsert<'_>> = ef
            .chunks
            .iter()
            .zip(emb_bytes.iter())
            .map(|(c, emb)| {
                let simhash = neuroncite_search::compute_simhash(&c.content);
                ChunkInsert {
                    file_id,
                    session_id,
                    page_start: c.page_start as i64,
                    page_end: c.page_end as i64,
                    chunk_index: c.chunk_index as i64,
                    doc_text_offset_start: c.doc_text_offset_start as i64,
                    doc_text_offset_end: c.doc_text_offset_end as i64,
                    content: &c.content,
                    embedding: Some(emb.as_slice()),
                    ext_offset: None,
                    ext_length: None,
                    content_hash: &c.content_hash,
                    simhash: Some(simhash as i64),
                }
            })
            .collect();

        store::bulk_insert_chunks(&conn, &chunk_inserts).expect("chunk insert failed");
    }

    let raw_embeddings =
        store::load_embeddings_for_hnsw(&conn, session_id).expect("load embeddings for HNSW");

    assert!(
        !raw_embeddings.is_empty(),
        "at least some chunk embeddings must be stored in the database"
    );

    let f32_vectors: Vec<(i64, Vec<f32>)> = raw_embeddings
        .into_iter()
        .map(|(id, bytes)| {
            let floats: Vec<f32> = bytes
                .chunks_exact(4)
                .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
                .collect();
            (id, floats)
        })
        .collect();

    let labeled: Vec<(i64, &[f32])> = f32_vectors
        .iter()
        .map(|(id, v)| (*id, v.as_slice()))
        .collect();
    let hnsw = neuroncite_store::build_hnsw(&labeled, 4).expect("build_hnsw");

    let query = vec![1.0_f32, 0.0, 0.0, 0.0];
    let results = hnsw.search(&query, 5, 64);

    assert!(
        !results.is_empty(),
        "HNSW query must return at least one result"
    );

    for (chunk_id, _distance) in &results {
        let exists: bool = conn
            .query_row(
                "SELECT EXISTS(SELECT 1 FROM chunk WHERE id = ?1)",
                rusqlite::params![chunk_id],
                |row| row.get(0),
            )
            .expect("chunk existence query failed");
        assert!(
            exists,
            "HNSW result chunk ID {chunk_id} must exist in the chunk table"
        );
    }

    eprintln!(
        "HNSW: built from {} vectors, query returned {} results",
        f32_vectors.len(),
        results.len()
    );
}
