// NeuronCite -- local, privacy-preserving semantic document search engine.
// Copyright (C) 2026 NeuronCite Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! Native OS window with embedded WebView for the NeuronCite frontend.
//!
//! Uses tao for window management (Win32/Cocoa/GTK) and wry for WebView
//! embedding (WebView2 on Windows, WebKit on macOS/Linux). Provides two
//! entry points:
//!
//! - [`run_gui_with_splash`]: Shows a transparent splash screen displaying a
//!   pre-rendered PNG of the "NeuronCite" logo during server startup, then
//!   transitions to the main application window once the server has bound its
//!   TCP listener and is ready to serve. The splash uses platform-native APIs
//!   (Win32 layered window, NSImageView, Cairo) instead of a WebView for
//!   instant appearance (~5ms) and reliable per-pixel alpha transparency.
//!
//! - [`open_native_window`]: Directly opens the main window at a known URL
//!   without a splash screen. Retained for cases where the server URL is
//!   already known (e.g. reconnecting to a running server).
//!
//! Both entry points create a frameless window with a custom titlebar
//! rendered by the SolidJS frontend. Window control buttons (minimize,
//! maximize/restore, close) communicate with the native layer via wry's
//! IPC channel using `window.ipc.postMessage()`.
//!
//! This module is conditionally compiled behind the `gui` feature flag.
//! When the feature is disabled, the existing browser-based launch via
//! the `opener` crate is used instead.
//!
//! **Threading constraint**: tao's event loop must run on the main thread
//! (platform requirement on macOS and Windows). The Axum HTTP server runs
//! in a background thread with its own tokio runtime.

use std::rc::Rc;

use tao::dpi::LogicalSize;
use tao::event::{Event, WindowEvent};
use tao::event_loop::{ControlFlow, EventLoopBuilder, EventLoopProxy};
use tao::platform::run_return::EventLoopExtRunReturn;
use tao::window::{Icon, WindowBuilder};
use wry::WebViewBuilder;

/// Embedded 256x256 RGBA PNG of the NeuronCite "C" icon with the brand's
/// purple-to-cyan gradient. Pre-generated by tools/gen/generate_icon.py.
/// Decoded at runtime to raw RGBA pixels for tao's Icon::from_rgba().
/// Used on macOS and Linux where there is no embedded resource mechanism.
#[cfg(not(target_os = "windows"))]
const ICON_PNG: &[u8] = include_bytes!("../assets/icon_256.png");

/// Decodes the embedded icon PNG and creates a tao Icon from the raw RGBA
/// pixel data. Returns None if decoding fails (should not happen with a
/// valid compile-time asset). Used on macOS and Linux for the window/dock
/// icon. On Windows, the icon is loaded from the exe's resource section
/// instead (see `apply_resource_icon`).
#[cfg(not(target_os = "windows"))]
fn load_window_icon() -> Option<Icon> {
    let img = image::load_from_memory(ICON_PNG).ok()?.into_rgba8();
    let (w, h) = img.dimensions();
    Icon::from_rgba(img.into_raw(), w, h).ok()
}

/// On Windows, returns None because the icon is set after window creation
/// via `apply_resource_icon`, which loads the multi-resolution ICO from
/// the exe's resource section (embedded by winres at link time). This
/// provides crisp icons at every DPI scaling level because Windows selects
/// the pre-rendered size closest to the actual display size, instead of
/// scaling a single 256x256 bitmap (which produces blocky edges on the
/// taskbar and window switcher).
#[cfg(target_os = "windows")]
fn load_window_icon() -> Option<Icon> {
    None
}

/// Loads the multi-resolution ICO from the Windows executable's resource
/// section (embedded by winres at link time) and sets it on the given window
/// via Win32 `WM_SETICON` messages for both the small icon (taskbar, title
/// bar) and the big icon (Alt+Tab, window switcher).
///
/// `LoadImageW` with `LR_DEFAULTSIZE` is NOT used -- instead, the exact
/// pixel sizes are queried from `GetSystemMetrics` (`SM_CXSMICON` for the
/// small icon slot, `SM_CXICON` for the big icon slot). These metrics
/// reflect the current DPI scaling, so at 150% DPI the small icon is 24x24
/// and the big icon is 48x48. `LoadImageW` extracts the closest matching
/// entry from the multi-resolution ICO and scales it to the requested size,
/// producing a crisp result because the ICO contains pre-rendered LANCZOS-
/// downscaled entries at 16, 24, 32, 48, 64, 128, and 256 pixels.
///
/// The resource ID 1 corresponds to the first (and only) icon resource
/// embedded by winres from `assets/icon.ico`.
#[cfg(target_os = "windows")]
fn apply_resource_icon(window: &tao::window::Window) {
    use tao::platform::windows::WindowExtWindows;
    use windows::Win32::Foundation::{HWND, LPARAM, WPARAM};
    use windows::Win32::System::LibraryLoader::GetModuleHandleW;
    use windows::Win32::UI::WindowsAndMessaging::{
        GetSystemMetrics, IMAGE_ICON, LR_SHARED, LoadImageW, SM_CXICON, SM_CXSMICON, SM_CYICON,
        SM_CYSMICON, SendMessageW, WM_SETICON,
    };
    use windows::core::PCWSTR;

    // ICON_SMALL (0) and ICON_BIG (1) are the wParam values for WM_SETICON.
    const ICON_SMALL: usize = 0;
    const ICON_BIG: usize = 1;

    // Resource ID 1 encoded as a PCWSTR. Win32 resource IDs below 0x10000 are
    // represented as integer atoms by casting the ID to a pointer value.
    // This is the standard MAKEINTRESOURCE(1) pattern.
    let resource_id = PCWSTR(std::ptr::dangling::<u16>());

    unsafe {
        let hinstance = match GetModuleHandleW(None) {
            Ok(h) => h,
            Err(_) => return,
        };

        // Get the native HWND from the tao window via the platform extension
        // trait. The trait returns isize; HWND wraps a raw pointer.
        let hwnd = HWND(window.hwnd() as *mut _);

        // Load the small icon at the DPI-appropriate size for the taskbar.
        // GetSystemMetrics returns the actual pixel size accounting for DPI.
        let small_cx = GetSystemMetrics(SM_CXSMICON);
        let small_cy = GetSystemMetrics(SM_CYSMICON);
        if let Ok(h) = LoadImageW(
            Some(hinstance.into()),
            resource_id,
            IMAGE_ICON,
            small_cx,
            small_cy,
            LR_SHARED,
        ) {
            SendMessageW(
                hwnd,
                WM_SETICON,
                Some(WPARAM(ICON_SMALL)),
                Some(LPARAM(h.0 as isize)),
            );
        }

        // Load the big icon at the DPI-appropriate size for Alt+Tab.
        let big_cx = GetSystemMetrics(SM_CXICON);
        let big_cy = GetSystemMetrics(SM_CYICON);
        if let Ok(h) = LoadImageW(
            Some(hinstance.into()),
            resource_id,
            IMAGE_ICON,
            big_cx,
            big_cy,
            LR_SHARED,
        ) {
            SendMessageW(
                hwnd,
                WM_SETICON,
                Some(WPARAM(ICON_BIG)),
                Some(LPARAM(h.0 as isize)),
            );
        }
    }
}

/// Custom user events for coordinating the splash screen lifecycle, server
/// readiness signals, and window close actions on the tao event loop.
///
/// These events are sent via `EventLoopProxy` from background threads (the
/// splash bridge thread and the WebView IPC handler) to the main thread's
/// event loop, which cannot be directly controlled from those contexts.
enum UserEvent {
    /// The server thread finished binding its TCP listener and is serving
    /// requests. Contains the localhost URL (with the actual bound port)
    /// that the main WebView should load.
    ServerReady(String),

    /// The server thread terminated during startup (database initialization
    /// failure, port binding failure, etc.) without providing a URL. The
    /// event loop should clean up and exit.
    ServerFailed,

    /// Frontend requested window close via the custom titlebar close button
    /// (IPC `window.ipc.postMessage("close")`).
    CloseRequested,
}

/// Dark navy background color matching the application's Dark Neon Tech
/// design theme. Used for the main application window's WebView background
/// to prevent a white flash while the SolidJS frontend loads from the
/// server URL.
///
/// RGB components: R=10, G=15, B=26 (#0a0f1a), fully opaque (A=255).
const MAIN_WINDOW_BG: (u8, u8, u8, u8) = (10, 15, 26, 255);

// ---------------------------------------------------------------------------
// Linux Wayland compatibility
// ---------------------------------------------------------------------------

/// On Linux under a Wayland session, forces GTK to use the X11 backend via
/// XWayland. wry 0.54 + tao 0.34 cannot create a WebView from a Wayland
/// window handle (`raw-window-handle` kind mismatch). Setting
/// `GDK_BACKEND=x11` before GTK initialisation makes tao create an X11
/// window through XWayland, which wry can handle.
///
/// No-op when:
/// - The platform is not Linux.
/// - `WAYLAND_DISPLAY` is not set (already running on X11).
/// - `GDK_BACKEND` is already set by the user (respects explicit override).
#[cfg(target_os = "linux")]
fn ensure_x11_backend() {
    if std::env::var_os("WAYLAND_DISPLAY").is_some() && std::env::var_os("GDK_BACKEND").is_none() {
        tracing::info!(
            "Wayland session detected; setting GDK_BACKEND=x11 for WebView compatibility"
        );
        // SAFETY: Called before any GTK or event-loop initialisation.
        // No other threads that read this variable have been spawned yet.
        unsafe {
            std::env::set_var("GDK_BACKEND", "x11");
        }
    }
}

#[cfg(not(target_os = "linux"))]
fn ensure_x11_backend() {}

// ---------------------------------------------------------------------------
// Pre-flight GUI availability check
// ---------------------------------------------------------------------------

/// Checks whether the native GUI can be created on the current platform.
///
/// On Linux, verifies that `libwebkit2gtk-4.1.so.0` can be dynamically loaded.
/// wry requires this library at runtime; if it is missing, the WebView
/// constructor fails with an opaque dlopen error. Checking upfront lets the
/// caller fall back to browser mode *before* consuming the shutdown channel.
///
/// On macOS and Windows this always returns `Ok(())` (WebKit is bundled with
/// macOS; WebView2 is pre-installed on modern Windows).
///
/// # Errors
///
/// Returns a human-readable error string describing what is missing and how
/// to install it.
pub fn preflight_gui_check() -> Result<(), String> {
    #[cfg(target_os = "linux")]
    {
        let lib = std::ffi::CString::new("libwebkit2gtk-4.1.so.0").unwrap();
        let handle = unsafe { libc::dlopen(lib.as_ptr(), libc::RTLD_LAZY) };
        if handle.is_null() {
            return Err(
                "WebKitGTK runtime library not found (libwebkit2gtk-4.1.so.0).\n\
                 Install with: sudo apt install libwebkit2gtk-4.1-0\n\
                 Or use headless mode: neuroncite serve"
                    .into(),
            );
        }
        // Close the handle immediately -- we only needed to test loadability.
        unsafe {
            libc::dlclose(handle);
        }
    }
    Ok(())
}

/// Launches the native GUI with a transparent splash screen shown during
/// server startup, transitioning to the main application window once the
/// server is ready.
///
/// **Lifecycle:**
///
/// 1. A compact (480x180), frameless, transparent splash window appears
///    centered on the primary monitor. A pre-rendered PNG with the
///    "NeuronCite" logo (purple-to-cyan gradient, gaussian glow) is
///    rendered using platform-native APIs -- the desktop is visible behind
///    the transparent areas. No WebView is used for the splash.
/// 2. A bridge thread blocks on `url_rx` waiting for the server thread to
///    send its bound URL. When received, it forwards the URL as a
///    `UserEvent::ServerReady` to the tao event loop.
/// 3. On `ServerReady`: the splash window is destroyed, and the full-size
///    main application window (1280x800, frameless, with WebView) is created,
///    pointing to the server URL.
/// 4. On `ServerFailed`: the splash is destroyed and the event loop exits.
/// 5. On window close (native Alt+F4 or IPC close command): `shutdown_tx`
///    fires to signal the server, and the event loop exits.
///
/// This function blocks the calling thread until the user closes the main
/// window (or the server fails during startup), then returns control to the
/// caller. It must be called from the main thread (platform requirement for
/// tao on macOS and Windows).
///
/// # Parameters
///
/// - `url_rx`: Receives the server URL (with actual bound port) from the
///   server thread after it finishes binding. If the sender is dropped before
///   sending (server startup failure), this receiver yields `RecvError`.
/// - `shutdown_tx`: Oneshot channel sender that signals the server to begin
///   graceful shutdown when the window is closed.
///
/// # Errors
///
/// Returns an error if the event loop, splash window, or bridge thread
/// cannot be created. Errors during main window creation (after the splash)
/// are handled internally by signaling shutdown and exiting the event loop.
#[allow(unused_assignments)]
pub fn run_gui_with_splash(
    url_rx: std::sync::mpsc::Receiver<String>,
    shutdown_tx: tokio::sync::oneshot::Sender<()>,
) -> Result<(), Box<dyn std::error::Error>> {
    ensure_x11_backend();

    let mut event_loop = EventLoopBuilder::<UserEvent>::with_user_event().build();

    // EventLoopProxy allows background threads to send custom events to the
    // event loop's main handler. The proxy is cloned for the bridge thread
    // and later for the WebView IPC handler when the main window is created.
    let proxy: EventLoopProxy<UserEvent> = event_loop.create_proxy();

    // Load the application icon for macOS and Linux from the embedded PNG.
    // On Windows, load_window_icon() returns None because the icon is applied
    // after window creation via apply_resource_icon(), which loads the multi-
    // resolution ICO from the exe's resource section for crisp DPI scaling.
    let window_icon = load_window_icon();

    // --- Create splash window ---
    //
    // The splash is a compact 480x180 frameless transparent window displayed
    // in the center of the primary monitor. A pre-rendered PNG with the
    // "NeuronCite" brand logo (gradient text + glow effect) is painted onto
    // the window using platform-native APIs (Win32 UpdateLayeredWindow,
    // macOS NSImageView, Linux GTK/Cairo). The desktop is visible behind
    // transparent areas of the PNG.
    //
    // No WebView is created for the splash -- this eliminates the ~300ms
    // WebView2 initialization delay and the associated white flash on Windows.
    // On Linux, tao's default transparent background draw handler must be
    // disabled so the splash module's Cairo draw handler has full control.
    // The cfg_attr applies with_transparent_draw(false) only on Linux.
    #[cfg(not(target_os = "linux"))]
    let splash_builder = WindowBuilder::new()
        .with_title("NeuronCite")
        .with_decorations(false)
        .with_resizable(false)
        .with_always_on_top(true)
        .with_transparent(true)
        .with_window_icon(window_icon.clone())
        .with_inner_size(LogicalSize::new(480.0, 180.0));

    #[cfg(target_os = "linux")]
    let splash_builder = {
        use tao::platform::unix::WindowBuilderExtUnix;
        WindowBuilder::new()
            .with_title("NeuronCite")
            .with_decorations(false)
            .with_resizable(false)
            .with_always_on_top(true)
            .with_transparent(true)
            .with_window_icon(window_icon.clone())
            .with_inner_size(LogicalSize::new(480.0, 180.0))
            .with_transparent_draw(false)
    };

    let splash_window = Rc::new(splash_builder.build(&event_loop)?);

    // On Windows, set the window icon from the exe's multi-resolution ICO
    // resource. This replaces tao's default (no icon) with the pre-rendered
    // sizes matching the current DPI scaling.
    #[cfg(target_os = "windows")]
    apply_resource_icon(&splash_window);

    // Center the splash window on the primary monitor. Uses physical pixel
    // coordinates from the monitor geometry and window outer size to compute
    // the centered position.
    if let Some(monitor) = splash_window.current_monitor() {
        let monitor_pos = monitor.position();
        let monitor_size = monitor.size();
        let window_size = splash_window.outer_size();
        let x = monitor_pos.x + (monitor_size.width as i32 - window_size.width as i32) / 2;
        let y = monitor_pos.y + (monitor_size.height as i32 - window_size.height as i32) / 2;
        splash_window.set_outer_position(tao::dpi::PhysicalPosition::new(x, y));
    }

    // Render the transparent PNG onto the splash window using platform-native
    // APIs. The PNG is embedded in the binary via include_bytes! and decoded
    // to RGBA pixels at runtime. If rendering fails (e.g. GDI error on Windows,
    // missing compositor on Linux), the window remains with whatever default
    // background the platform provides -- acceptable as graceful degradation
    // for a transient splash that displays for 1-3 seconds.
    if let Err(e) = crate::splash::render_splash_on_window(&splash_window) {
        tracing::warn!("transparent splash rendering failed, using fallback: {e}");
    }

    // --- Bridge thread ---
    //
    // Blocks on the std::sync::mpsc channel waiting for the server thread to
    // send its bound URL. Forwards the result as a UserEvent to the event
    // loop so the main thread can transition from splash to main window.
    // If the server thread terminates during setup (dropping url_tx without
    // sending), the recv() returns Err and ServerFailed is dispatched.
    let bridge_proxy = event_loop.create_proxy();
    std::thread::Builder::new()
        .name("splash-bridge".into())
        .spawn(move || match url_rx.recv() {
            Ok(url) => {
                let _ = bridge_proxy.send_event(UserEvent::ServerReady(url));
            }
            Err(_) => {
                let _ = bridge_proxy.send_event(UserEvent::ServerFailed);
            }
        })?;

    // --- Event loop state ---
    //
    // Mutable state tracked across event loop iterations. The splash window
    // is stored in an Option so it can be destroyed when the server is ready.
    // The splash holds only the tao Window (no WebView). The main window
    // holds both the Window and its WebView.
    let mut splash: Option<Rc<tao::window::Window>> = Some(splash_window);
    // Holds the main window and WebView to keep them alive while the event
    // loop runs. The WebView is stored as the first tuple element so it is
    // dropped before the Window (child before parent). On macOS, the WebView
    // (WKWebView) must be dropped while the Cocoa run loop is still active,
    // because its destructor dispatches cleanup messages to the main thread.
    // If the WebView were dropped after ControlFlow::Exit (when the run loop
    // has stopped), those dispatched messages would never be processed,
    // causing a deadlock. The explicit take() in the CloseRequested handler
    // ensures destruction happens while the run loop can still pump events.
    let mut _main_state: Option<(wry::WebView, Rc<tao::window::Window>)> = None;
    let mut shutdown_tx = Some(shutdown_tx);

    // run_return (from EventLoopExtRunReturn) returns control to the caller
    // after ControlFlow::Exit is set, instead of diverging like EventLoop::run.
    let _exit_code = event_loop.run_return(move |event, event_loop_target, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            // --- Phase transition: server is ready, swap splash for main window ---
            Event::UserEvent(UserEvent::ServerReady(url)) => {
                // Drop the splash window. Dropping the Rc<Window> (the last
                // reference) destroys the OS window and releases platform
                // resources (GDI objects on Windows, NSWindow on macOS,
                // GTK window on Linux).
                splash.take();

                // On Windows, set the WebView2 default background color via
                // environment variable BEFORE creating the main WebView
                // controller. The WebView2 runtime reads this variable during
                // controller initialization and applies it as the initial
                // background color, preventing the default white from showing
                // while the SolidJS app loads. Format: AARRGGBB hex.
                #[cfg(target_os = "windows")]
                // SAFETY: Called on the main thread. The splash had no WebView,
                // so this is the first WebView2 controller being created.
                unsafe {
                    std::env::set_var("WEBVIEW2_DEFAULT_BACKGROUND_COLOR", "FF0A0F1A");
                }

                // Create the main application window with the same configuration
                // as open_native_window: frameless, 1280x800 default size, 900x600
                // minimum. If creation fails, signal shutdown and exit.
                let window = match WindowBuilder::new()
                    .with_title("NeuronCite")
                    .with_decorations(false)
                    .with_window_icon(window_icon.clone())
                    .with_inner_size(LogicalSize::new(1280.0, 800.0))
                    .with_min_inner_size(LogicalSize::new(900.0, 600.0))
                    .build(event_loop_target)
                {
                    Ok(w) => Rc::new(w),
                    Err(e) => {
                        eprintln!("ERROR [gui_init] failed to create main window: {e}");
                        if let Some(tx) = shutdown_tx.take() {
                            let _ = tx.send(());
                        }
                        *control_flow = ControlFlow::Exit;
                        return;
                    }
                };

                // On Windows, override the window icon with the multi-resolution
                // ICO from the exe resources for crisp taskbar rendering.
                #[cfg(target_os = "windows")]
                apply_resource_icon(&window);

                // Clone Rc and proxy for the IPC handler closure. The IPC handler
                // runs in the WebView callback context on the main thread and
                // processes window control commands from the frontend's custom
                // titlebar buttons.
                let ipc_window = Rc::clone(&window);
                let ipc_proxy = proxy.clone();

                // The WebView renders the SolidJS frontend served by the local
                // Axum server. Communication between frontend and backend happens
                // via HTTP REST + SSE through the same localhost URL. The IPC
                // channel is used exclusively for window management commands.
                //
                // `with_background_color` sets the initial WebView background to
                // the dark navy, preventing a white flash while the SolidJS app
                // loads. The SolidJS app has the same dark background in its CSS.
                //
                // The navigation handler restricts all WebView navigation to the
                // server's own origin (http://127.0.0.1:PORT). Any attempt to
                // navigate away from this origin -- whether from a link in the
                // frontend, a redirect, or a compromised page -- is rejected.
                // External URLs are opened via the system browser through the IPC
                // `open_url:` command instead.
                let allowed_origin = url.clone();
                let webview = match WebViewBuilder::new()
                    .with_url(&url)
                    .with_background_color(MAIN_WINDOW_BG)
                    .with_devtools(cfg!(debug_assertions))
                    .with_navigation_handler(move |nav_url: String| {
                        // Allow navigation only to the server's own origin.
                        // The initial page load and all SPA route changes use
                        // the same origin, so this allows all legitimate navigation
                        // while blocking any attempt to load external resources.
                        nav_url.starts_with(&allowed_origin)
                    })
                    .with_ipc_handler(move |request: wry::http::Request<String>| {
                        match request.body().as_str() {
                            "minimize" => {
                                ipc_window.set_minimized(true);
                            }
                            "maximize" => {
                                // Toggle between maximized and restored state.
                                let is_maximized = ipc_window.is_maximized();
                                ipc_window.set_maximized(!is_maximized);
                            }
                            "close" => {
                                let _ = ipc_proxy.send_event(UserEvent::CloseRequested);
                            }
                            "drag" => {
                                // Initiate an OS-native window drag operation.
                                // On macOS, -webkit-app-region CSS is not supported
                                // by WKWebView, so the frontend sends this IPC command
                                // on mousedown in the topbar drag region instead.
                                let _ = ipc_window.drag_window();
                            }
                            cmd if cmd.starts_with("open_url:") => {
                                // Open external URLs in the system default browser.
                                // Only http and https schemes are permitted; any other
                                // scheme (file://, javascript:, etc.) is silently rejected
                                // to prevent the IPC channel from being used as a vector
                                // for local file access or script injection.
                                let url = cmd.trim_start_matches("open_url:");
                                if url.starts_with("https://") || url.starts_with("http://") {
                                    let _ = opener::open(url);
                                } else {
                                    tracing::warn!(
                                        url = url,
                                        "IPC open_url rejected: non-http/https scheme"
                                    );
                                }
                            }
                            _ => {}
                        }
                    })
                    .build(&window)
                {
                    Ok(wv) => wv,
                    Err(e) => {
                        eprintln!("ERROR [gui_init] failed to create WebView: {e}");
                        #[cfg(target_os = "windows")]
                        eprintln!(
                            "On Windows, this typically means Microsoft WebView2 Runtime is not installed.\n\
                             Download from: https://developer.microsoft.com/en-us/microsoft-edge/webview2/"
                        );
                        #[cfg(target_os = "linux")]
                        eprintln!(
                            "On Linux, this typically means WebKitGTK is not installed or the display\n\
                             server does not support the window handle type used by this build.\n\
                             \n\
                             Install WebKitGTK:   sudo apt install libwebkit2gtk-4.1-0\n\
                             Force X11 backend:   GDK_BACKEND=x11 neuroncite\n\
                             Use headless mode:   neuroncite serve"
                        );
                        if let Some(tx) = shutdown_tx.take() {
                            let _ = tx.send(());
                        }
                        *control_flow = ControlFlow::Exit;
                        return;
                    }
                };

                // Store the WebView and Window to keep them alive for the
                // remainder of the event loop. WebView is first so it is
                // dropped before the Window when _main_state.take() is called
                // in the close handler. This ordering is required on macOS
                // where WKWebView's destructor must complete while the Window
                // (and its Cocoa run loop) is still alive.
                _main_state = Some((webview, window));
            }

            // --- Server startup failure: clean up and exit ---
            Event::UserEvent(UserEvent::ServerFailed) => {
                // Drop the splash window. The server already terminated, so
                // shutdown_tx is not sent (the server's shutdown_rx will receive
                // RecvError when shutdown_tx is dropped at closure cleanup).
                splash.take();
                *control_flow = ControlFlow::Exit;
            }

            // --- Window close: native close event or IPC close command ---
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            }
            | Event::UserEvent(UserEvent::CloseRequested) => {
                // Drop the WebView and Window while the Cocoa run loop is
                // still active. On macOS, WKWebView's destructor dispatches
                // cleanup messages to the main thread via dispatch_async.
                // These messages require the run loop to be pumping events.
                // If ControlFlow::Exit is set first, run_return() calls
                // [NSApp stop:] and the run loop stops -- the dispatched
                // messages are never processed, causing a deadlock. Dropping
                // here (before Exit) ensures the run loop processes all
                // cleanup messages before stopping.
                // On Windows and Linux this ordering is not required but
                // does no harm -- resources are released slightly earlier.
                _main_state.take();
                splash.take();

                // Signal the Axum server to shut down gracefully. The oneshot
                // channel fires once; if it was already consumed, the take()
                // returns None and no duplicate signal is sent.
                if let Some(tx) = shutdown_tx.take() {
                    let _ = tx.send(());
                }
                *control_flow = ControlFlow::Exit;
            }

            _ => {}
        }
    });

    Ok(())
}

/// Opens a frameless native OS window with an embedded WebView pointing to
/// the given URL. The window has no native titlebar or decorations -- the
/// SolidJS frontend renders a custom titlebar with drag region and window
/// control buttons.
///
/// The IPC handler listens for messages from `window.ipc.postMessage()` in
/// the frontend and dispatches window control actions:
///
/// - `"minimize"`: Minimizes the window to the taskbar/dock
/// - `"maximize"`: Toggles between maximized and restored window state
/// - `"close"`: Sends a UserEvent::CloseRequested to the event loop
///
/// This function blocks the calling thread until the user closes the window,
/// then returns control to the caller. It must be called from the main thread
/// (platform requirement for tao on macOS and Windows).
///
/// Uses `EventLoopExtRunReturn::run_return` instead of `EventLoop::run` so
/// that the function returns after the window closes rather than diverging.
/// This allows the caller to perform cleanup (e.g. joining the server thread).
///
/// When the window is closed, `shutdown_tx` fires a signal that the Axum
/// server (running in a background thread) uses to initiate graceful shutdown.
///
/// # Errors
///
/// Returns an error if the event loop, window, or WebView cannot be created.
/// Common failure causes: missing WebView2 runtime on Windows, missing
/// WebKitGTK on Linux, or insufficient display server access.
pub fn open_native_window(
    url: &str,
    shutdown_tx: tokio::sync::oneshot::Sender<()>,
) -> Result<(), Box<dyn std::error::Error>> {
    ensure_x11_backend();

    let mut event_loop = EventLoopBuilder::<UserEvent>::with_user_event().build();

    // EventLoopProxy allows the IPC handler (which runs in the WebView
    // callback context) to send custom events to the event loop's main
    // handler. This bridges the gap between the IPC closure and the
    // event loop's ControlFlow mechanism.
    let proxy: EventLoopProxy<UserEvent> = event_loop.create_proxy();

    // Load the application icon for macOS/Linux. On Windows, returns None
    // because the icon is applied after window creation from exe resources.
    let window_icon = load_window_icon();

    // Rc<Window> enables shared ownership between the event loop closure
    // and the IPC handler closure. Both closures run on the main thread
    // (tao requirement), so Rc is sufficient -- no Arc needed.
    let window = Rc::new(
        WindowBuilder::new()
            .with_title("NeuronCite")
            .with_decorations(false)
            .with_window_icon(window_icon)
            .with_inner_size(LogicalSize::new(1280.0, 800.0))
            .with_min_inner_size(LogicalSize::new(900.0, 600.0))
            .build(&event_loop)?,
    );

    // On Windows, set the window icon from the exe's multi-resolution ICO
    // resource for crisp taskbar and Alt+Tab rendering at any DPI scaling.
    #[cfg(target_os = "windows")]
    apply_resource_icon(&window);

    // Clone the Rc for the IPC handler closure. The IPC handler processes
    // window control commands sent from the frontend via
    // window.ipc.postMessage(). Each command maps to a tao Window method.
    let ipc_window = Rc::clone(&window);

    // The WebView renders the SolidJS frontend served by the local Axum
    // server. Communication between frontend and backend happens via
    // HTTP REST + SSE through the same localhost URL. The IPC channel
    // is used exclusively for window management commands.
    //
    // `with_background_color` sets the initial WebView background to the
    // dark navy (#0a0f1a), preventing a white flash while the SolidJS app
    // loads from the server URL.
    //
    // The navigation handler restricts all WebView navigation to the
    // server's own origin (http://127.0.0.1:PORT). Any attempt to
    // navigate away from this origin -- whether from a link in the
    // frontend, a redirect, or a compromised page -- is rejected.
    // External URLs are opened via the system browser through the IPC
    // `open_url:` command instead.
    let allowed_origin = url.to_string();
    let webview = WebViewBuilder::new()
        .with_url(url)
        .with_background_color(MAIN_WINDOW_BG)
        .with_devtools(cfg!(debug_assertions))
        .with_navigation_handler(move |nav_url: String| {
            // Allow navigation only to the server's own origin.
            // The initial page load and all SPA route changes use
            // the same origin, so this allows all legitimate navigation
            // while blocking any attempt to load external resources.
            nav_url.starts_with(&allowed_origin)
        })
        .with_ipc_handler(move |request: wry::http::Request<String>| {
            // The frontend sends the command as the request body string via
            // window.ipc.postMessage("command"). The body contains the raw
            // command without any JSON wrapping.
            match request.body().as_str() {
                "minimize" => {
                    ipc_window.set_minimized(true);
                }
                "maximize" => {
                    // Toggle between maximized and restored state. When the
                    // window is already maximized, restore it to its previous
                    // size and position; otherwise maximize it.
                    let is_maximized = ipc_window.is_maximized();
                    ipc_window.set_maximized(!is_maximized);
                }
                "close" => {
                    // Send a custom event to the event loop to trigger
                    // shutdown. Cannot set ControlFlow directly from here
                    // because the IPC handler runs outside the event loop
                    // dispatch cycle.
                    let _ = proxy.send_event(UserEvent::CloseRequested);
                }
                "drag" => {
                    // Initiate an OS-native window drag operation.
                    // On macOS, -webkit-app-region CSS is not supported
                    // by WKWebView, so the frontend sends this IPC command
                    // on mousedown in the topbar drag region instead.
                    let _ = ipc_window.drag_window();
                }
                cmd if cmd.starts_with("open_url:") => {
                    // Open external URLs in the system default browser.
                    // Only http and https schemes are permitted; any other
                    // scheme (file://, javascript:, etc.) is silently rejected
                    // to prevent the IPC channel from being used as a vector
                    // for local file access or script injection.
                    let url = cmd.trim_start_matches("open_url:");
                    if url.starts_with("https://") || url.starts_with("http://") {
                        let _ = opener::open(url);
                    } else {
                        tracing::warn!(url = url, "IPC open_url rejected: non-http/https scheme");
                    }
                }
                _ => {}
            }
        })
        .build(&window)?;

    // WebView and Window are wrapped in an Option so they can be explicitly
    // dropped in the close handler while the Cocoa run loop is still active.
    // See the comment in run_gui_with_splash for the macOS deadlock rationale.
    // WebView is the first tuple element so it is dropped before the Window.
    let mut window_state: Option<(wry::WebView, Rc<tao::window::Window>)> = Some((webview, window));

    // Wrap shutdown_tx in Option so the closure can take ownership exactly once
    // when the window close event fires. Subsequent close events (if any) are
    // ignored because the Option is already None.
    let mut shutdown_tx = Some(shutdown_tx);

    // run_return (from EventLoopExtRunReturn) returns control to the caller
    // after ControlFlow::Exit is set, instead of diverging like EventLoop::run.
    // On Unix, returns 1 if the display server disconnects unexpectedly.
    let _exit_code = event_loop.run_return(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            // Native close event (e.g. Alt+F4, taskbar close on Windows)
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            }
            // Custom event from the IPC close handler in the frontend
            | Event::UserEvent(UserEvent::CloseRequested) => {
                // Drop WebView and Window while the run loop is still active.
                // On macOS, WKWebView's destructor dispatches cleanup messages
                // to the main thread. The run loop must be pumping to process
                // them. See run_gui_with_splash for the full explanation.
                window_state.take();

                // Signal the Axum server to shut down gracefully. The oneshot
                // channel fires once; if it was already consumed, the take()
                // returns None and no duplicate signal is sent.
                if let Some(tx) = shutdown_tx.take() {
                    let _ = tx.send(());
                }
                *control_flow = ControlFlow::Exit;
            }
            _ => {}
        }
    });

    Ok(())
}
