#!/usr/bin/env bash
# =============================================================================
# Build script for: reproducibility_crisis_ai.tex
# Compiles the LaTeX document, checks for errors and overfull warnings,
# cleans all intermediate artifacts, and removes the source Word document.
# =============================================================================

set -euo pipefail

BASENAME="reproducibility_crisis_ai"
TEX_FILE="${BASENAME}.tex"
PDF_FILE="${BASENAME}.pdf"
BIB_FILE="${BASENAME}.bib"
DOCX_FILE="Die Reproduzierbarkeitskrise in der Künstlichen Intelligenz_ Statistische Verzerrungen, Benchmark-Gr.docx"

# Intermediate files generated by pdflatex / bibtex
ARTIFACTS=(
  "${BASENAME}.aux"
  "${BASENAME}.bbl"
  "${BASENAME}.blg"
  "${BASENAME}.log"
  "${BASENAME}.out"
  "${BASENAME}.toc"
  "${BASENAME}.lof"
  "${BASENAME}.lot"
  "${BASENAME}.nav"
  "${BASENAME}.snm"
  "${BASENAME}.fdb_latexmk"
  "${BASENAME}.fls"
  "${BASENAME}.synctex.gz"
)

# Color codes for terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "============================================="
echo " Building ${TEX_FILE}"
echo "============================================="

# --- Step 1: First pdflatex pass (generates .aux for bibtex) -----------------
echo ""
echo "[1/4] Running pdflatex (first pass)..."
if ! pdflatex -interaction=nonstopmode -halt-on-error "${TEX_FILE}" > /dev/null 2>&1; then
  echo -e "${RED}[ERROR] First pdflatex pass failed.${NC}"
  echo "Full log:"
  cat "${BASENAME}.log" | grep -A 2 "^!" || cat "${BASENAME}.log"
  exit 1
fi
echo -e "${GREEN}       First pass completed.${NC}"

# --- Step 2: BibTeX pass (resolves citations) --------------------------------
echo "[2/4] Running bibtex..."
if ! bibtex "${BASENAME}" > /dev/null 2>&1; then
  echo -e "${YELLOW}[WARN] BibTeX reported issues. Checking .blg log:${NC}"
  cat "${BASENAME}.blg"
fi
echo -e "${GREEN}       BibTeX completed.${NC}"

# --- Step 3: Second pdflatex pass (integrates bibliography) ------------------
echo "[3/4] Running pdflatex (second pass)..."
pdflatex -interaction=nonstopmode -halt-on-error "${TEX_FILE}" > /dev/null 2>&1
echo -e "${GREEN}       Second pass completed.${NC}"

# --- Step 4: Third pdflatex pass (resolves all cross-references) -------------
echo "[4/4] Running pdflatex (third pass)..."
pdflatex -interaction=nonstopmode -halt-on-error "${TEX_FILE}" > /dev/null 2>&1
echo -e "${GREEN}       Third pass completed.${NC}"

# --- Check for errors --------------------------------------------------------
echo ""
echo "============================================="
echo " Checking for errors and warnings"
echo "============================================="

ERROR_COUNT=0
WARN_COUNT=0

# Check for LaTeX errors (lines starting with !)
if grep -q "^!" "${BASENAME}.log"; then
  echo -e "${RED}[ERRORS FOUND]${NC}"
  grep "^!" "${BASENAME}.log"
  ERROR_COUNT=$(grep -c "^!" "${BASENAME}.log")
fi

# Check for overfull hbox/vbox warnings
OVERFULL_COUNT=0
if grep -q "Overfull" "${BASENAME}.log"; then
  OVERFULL_COUNT=$(grep -c "Overfull" "${BASENAME}.log")
  echo -e "${YELLOW}[OVERFULL WARNINGS: ${OVERFULL_COUNT}]${NC}"
  grep "Overfull" "${BASENAME}.log"
fi

# Check for undefined references
if grep -q "undefined references" "${BASENAME}.log"; then
  echo -e "${YELLOW}[UNDEFINED REFERENCES]${NC}"
  grep "undefined" "${BASENAME}.log"
  WARN_COUNT=$((WARN_COUNT + 1))
fi

# Check for missing citations
if grep -q "Citation.*undefined" "${BASENAME}.log"; then
  echo -e "${YELLOW}[UNDEFINED CITATIONS]${NC}"
  grep "Citation.*undefined" "${BASENAME}.log"
  WARN_COUNT=$((WARN_COUNT + 1))
fi

if [ "$ERROR_COUNT" -eq 0 ] && [ "$OVERFULL_COUNT" -eq 0 ] && [ "$WARN_COUNT" -eq 0 ]; then
  echo -e "${GREEN}No errors, no overfull warnings, no undefined references.${NC}"
fi

# --- Verify PDF was created --------------------------------------------------
echo ""
if [ -f "${PDF_FILE}" ]; then
  PDF_SIZE=$(stat -c%s "${PDF_FILE}" 2>/dev/null || stat -f%z "${PDF_FILE}" 2>/dev/null || echo "unknown")
  echo -e "${GREEN}PDF created: ${PDF_FILE} (${PDF_SIZE} bytes)${NC}"
else
  echo -e "${RED}[ERROR] PDF was not created!${NC}"
  exit 1
fi

# --- Clean up intermediate artifacts -----------------------------------------
echo ""
echo "============================================="
echo " Cleaning intermediate artifacts"
echo "============================================="

for artifact in "${ARTIFACTS[@]}"; do
  if [ -f "${artifact}" ]; then
    rm -f "${artifact}"
    echo "  Removed: ${artifact}"
  fi
done

# --- Delete the source Word document -----------------------------------------
if [ -f "${DOCX_FILE}" ]; then
  rm -f "${DOCX_FILE}"
  echo "  Removed: ${DOCX_FILE}"
fi

echo ""
echo "============================================="
echo -e "${GREEN} Build complete. Output: ${PDF_FILE}${NC}"
echo "============================================="
echo ""
echo "Remaining files:"
ls -la
